-- Create Database and Schema
CREATE WAREHOUSE IF NOT EXISTS SCD
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
USE WAREHOUSE SCD;

CREATE DATABASE IF NOT EXISTS CUSTOMER_SCD_T3;
USE DATABASE CUSTOMER_SCD_T3;

CREATE SCHEMA IF NOT EXISTS SCD_SCHEMA;
USE SCHEMA SCD_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FF
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE CUSTOMER_STAGE
    FILE_FORMAT = CSV_FF;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR(100),
    CITY            VARCHAR(50),
    STATE           VARCHAR(50),
    MEMBERSHIP      VARCHAR(30),
    SEGMENT         VARCHAR(30),
    EFFECTIVE_DATE  DATE
);

COPY INTO CUSTOMER_UPDATES (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT, EFFECTIVE_DATE)
FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';


-- Create Type 3 Dimension

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE3 (
    CUSTOMER_KEY         NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_ID          NUMBER,
    CUSTOMER_NAME        VARCHAR(100),
    CITY                 VARCHAR(50),
    STATE                VARCHAR(50),
    CURRENT_MEMBERSHIP   VARCHAR(30),
    PREVIOUS_MEMBERSHIP  VARCHAR(30),
    SEGMENT              VARCHAR(30)
);


-- Load Initial Type 3 Data

COPY INTO DIM_CUSTOMER_TYPE3 (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP, SEGMENT)
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';

SELECT 'Initial Type 3 Records Loaded Successfully' AS STATUS,
       COUNT(*) AS TOTAL_CUSTOMERS
FROM DIM_CUSTOMER_TYPE3;

-- Display Initial Type 3 Data
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;


--Apply / Update SCD Type 3 Changes

UPDATE DIM_CUSTOMER_TYPE3 d
SET d.PREVIOUS_MEMBERSHIP = d.CURRENT_MEMBERSHIP,
    d.CURRENT_MEMBERSHIP  = u.MEMBERSHIP,
    d.CITY                = u.CITY,
    d.STATE               = u.STATE,
    d.SEGMENT             = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;


-- Type 3 Final Report
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

-- Demonstrate Type 3

SELECT CUSTOMER_ID, CUSTOMER_NAME, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
WHERE CUSTOMER_ID = 101;

-- Create Type 6 Dimension
CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE6 (
    CUSTOMER_KEY            NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_ID             NUMBER,
    CUSTOMER_NAME           VARCHAR(100),
    CITY                    VARCHAR(50),
    STATE                   VARCHAR(50),
    CURRENT_MEMBERSHIP      VARCHAR(30),
    PREVIOUS_MEMBERSHIP     VARCHAR(30),
    HISTORICAL_MEMBERSHIP   VARCHAR(30),
    SEGMENT                 VARCHAR(30),
    EFFECTIVE_DATE          DATE,
    EXPIRY_DATE             DATE,
    IS_CURRENT              BOOLEAN
);


-- Load Initial Type 6 Records
  
INSERT INTO DIM_CUSTOMER_TYPE6
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP,
     PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT,
     EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    customer_id, customer_name, city, state, membership,
    NULL, membership, segment,
    DATE '2026-01-01', DATE '9999-12-31', TRUE
FROM (
    SELECT $1 AS customer_id, $2 AS customer_name, $3 AS city,
           $4 AS state, $5 AS membership, $6 AS segment
    FROM @CUSTOMER_STAGE/customers_initial.csv
    (FILE_FORMAT => 'CSV_FF')
);
SELECT 'Initial Type 6 Records Loaded Successfully' AS STATUS,
       COUNT(*) AS TOTAL_RECORDS,
       SUM(IFF(IS_CURRENT, 1, 0)) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_TYPE6;


-- Apply Type 6 Changes
-- Step 1: Close existing current rows for changed customers
UPDATE DIM_CUSTOMER_TYPE6 d
SET d.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    d.IS_CURRENT  = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT  = TRUE;

-- Step 2: Insert new current rows carrying PREVIOUS_MEMBERSHIP forward
INSERT INTO DIM_CUSTOMER_TYPE6
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP,
     PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT,
     EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    u.CUSTOMER_ID, u.CUSTOMER_NAME, u.CITY, u.STATE, u.MEMBERSHIP,
    old.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,
    u.MEMBERSHIP            AS HISTORICAL_MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE, DATE '9999-12-31', TRUE
FROM CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_TYPE6 old
    ON old.CUSTOMER_ID = u.CUSTOMER_ID
   AND old.IS_CURRENT  = FALSE
   AND old.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE);


-- Display Complete Type 6 History

SELECT CUSTOMER_ID, CUSTOMER_NAME, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP,
       EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- Current Customer Report
   
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

--Point-in-Time Historical Query
  
SELECT CUSTOMER_ID, CUSTOMER_NAME, CURRENT_MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
  AND DATE '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

-- Type 3 vs Type 6
SELECT * FROM (
    SELECT 'Current Value'    AS FEATURE, 'YES' AS TYPE_3, 'YES' AS TYPE_6
    UNION ALL SELECT 'Previous Value',  'YES', 'YES'
    UNION ALL SELECT 'Historical Rows', 'NO',  'YES'
    UNION ALL SELECT 'Effective Date',  'NO',  'YES'
    UNION ALL SELECT 'Expiry Date',     'NO',  'YES'
    UNION ALL SELECT 'IS_CURRENT',      'NO',  'YES'
);

--Record Count Validation
SELECT 'SCD TYPE 3 RECORD COUNT' AS METRIC, COUNT(*) AS VALUE
FROM DIM_CUSTOMER_TYPE3

UNION ALL

SELECT 'SCD TYPE 6 RECORD COUNT', COUNT(*)
FROM DIM_CUSTOMER_TYPE6

UNION ALL

SELECT 'SCD TYPE 6 CURRENT RECORD COUNT', COUNT(*)
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT 'SCD TYPE 6 HISTORICAL RECORD COUNT', COUNT(*)
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = FALSE;
