--Create Database and Schema
CREATE WAREHOUSE IF NOT EXISTS SCD
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
USE WAREHOUSE SCD;

CREATE DATABASE IF NOT EXISTS CUSTOMER_SCD_AT;
USE DATABASE CUSTOMER_SCD_AT;

CREATE SCHEMA IF NOT EXISTS SCD_SCHEMA;
USE SCHEMA SCD_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FF
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE CUSTOMER_STAGE
    FILE_FORMAT = CSV_FF;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR(100),
    CITY            VARCHAR(50),
    STATE           VARCHAR(50),
    MEMBERSHIP      VARCHAR(30),
    SEGMENT         VARCHAR(30),
    EFFECTIVE_DATE  DATE
);

COPY INTO CUSTOMER_UPDATES (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT, EFFECTIVE_DATE)
FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';


-- Create Hybrid Dimension Table
   
CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY            NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_ID             NUMBER,
    CUSTOMER_NAME           VARCHAR(100),
    CITY                    VARCHAR(50),   -- current city, globally synced
    PREVIOUS_CITY           VARCHAR(50),   -- immediate prior city
    STATE                   VARCHAR(50),   -- overwritten directly, globally synced
    CURRENT_MEMBERSHIP      VARCHAR(30),   -- current active membership, globally synced
    PREVIOUS_MEMBERSHIP     VARCHAR(30),   -- immediate prior membership, globally synced
    HISTORICAL_MEMBERSHIP   VARCHAR(30),   -- per-row slice value (what was true then)
    SEGMENT                 VARCHAR(30),   -- per-row slice value
    EFFECTIVE_DATE          DATE,
    EXPIRY_DATE             DATE,
    IS_CURRENT              BOOLEAN
);


-- Load Initial Dimension Data
INSERT INTO DIM_CUSTOMER_HYBRID
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
     CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT,
     EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    $1, $2, $3, NULL, $4,
    $5, NULL, $5, $6,
    DATE '2026-01-01', DATE '9999-12-31', TRUE
FROM @CUSTOMER_STAGE/customers_initial.csv
    (FILE_FORMAT => 'CSV_FF');

SELECT 'Initial Hybrid Dimension Data Loaded Successfully' AS STATUS,
       COUNT(*) AS TOTAL_RECORDS,
       SUM(IFF(IS_CURRENT, 1, 0)) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_HYBRID;


-- Display Initial Dimension State
 
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
       CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
       SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;

-- Apply Hybrid Updates for Customers 101, 103, and 104
-- Step 1: Expire active versions (one statement per customer) 

UPDATE DIM_CUSTOMER_HYBRID d
SET d.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    d.IS_CURRENT  = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT  = TRUE
  AND d.CUSTOMER_ID = 101;

UPDATE DIM_CUSTOMER_HYBRID d
SET d.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    d.IS_CURRENT  = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT  = TRUE
  AND d.CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_HYBRID d
SET d.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    d.IS_CURRENT  = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT  = TRUE
  AND d.CUSTOMER_ID = 104;
-- Step 2: Insert new active versions (single statement, 3 rows) 

INSERT INTO DIM_CUSTOMER_HYBRID
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
     CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
     SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    u.CUSTOMER_ID, u.CUSTOMER_NAME,
    u.CITY,                       -- new current city
    old.CITY AS PREVIOUS_CITY,    -- old row's city (pre-sync) = prior city
    u.STATE,                      -- overwritten directly
    u.MEMBERSHIP AS CURRENT_MEMBERSHIP,
    old.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,  -- old row's membership = prior membership
    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,          -- slice value for this row
    u.SEGMENT,
    u.EFFECTIVE_DATE, DATE '9999-12-31', TRUE
FROM CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_HYBRID old
    ON old.CUSTOMER_ID = u.CUSTOMER_ID
   AND old.IS_CURRENT  = FALSE
   AND old.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE);
-- number of rows inserted: 3

-- Step 3: Synchronize global attributes across ALL versions

UPDATE DIM_CUSTOMER_HYBRID d
SET d.CITY                 = cur.CITY,
    d.PREVIOUS_CITY        = cur.PREVIOUS_CITY,
    d.STATE                = cur.STATE,
    d.CURRENT_MEMBERSHIP   = cur.CURRENT_MEMBERSHIP,
    d.PREVIOUS_MEMBERSHIP  = cur.PREVIOUS_MEMBERSHIP
FROM (
    SELECT CITY, PREVIOUS_CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
    FROM DIM_CUSTOMER_HYBRID
    WHERE CUSTOMER_ID = 101 AND IS_CURRENT = TRUE
) cur
WHERE d.CUSTOMER_ID = 101;

UPDATE DIM_CUSTOMER_HYBRID d
SET d.CITY                 = cur.CITY,
    d.PREVIOUS_CITY        = cur.PREVIOUS_CITY,
    d.STATE                = cur.STATE,
    d.CURRENT_MEMBERSHIP   = cur.CURRENT_MEMBERSHIP,
    d.PREVIOUS_MEMBERSHIP  = cur.PREVIOUS_MEMBERSHIP
FROM (
    SELECT CITY, PREVIOUS_CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
    FROM DIM_CUSTOMER_HYBRID
    WHERE CUSTOMER_ID = 103 AND IS_CURRENT = TRUE
) cur
WHERE d.CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_HYBRID d
SET d.CITY                 = cur.CITY,
    d.PREVIOUS_CITY        = cur.PREVIOUS_CITY,
    d.STATE                = cur.STATE,
    d.CURRENT_MEMBERSHIP   = cur.CURRENT_MEMBERSHIP,
    d.PREVIOUS_MEMBERSHIP  = cur.PREVIOUS_MEMBERSHIP
FROM (
    SELECT CITY, PREVIOUS_CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
    FROM DIM_CUSTOMER_HYBRID
    WHERE CUSTOMER_ID = 104 AND IS_CURRENT = TRUE
) cur
WHERE d.CUSTOMER_ID = 104;

SELECT 'Hybrid SCD Updates Applied Successfully' AS STATUS,
       COUNT(*) AS TOTAL_RECORDS,
       SUM(IFF(IS_CURRENT, 1, 0)) AS CURRENT_RECORDS,
       SUM(IFF(IS_CURRENT, 0, 1)) AS HISTORICAL_RECORDS
FROM DIM_CUSTOMER_HYBRID;


-- Display Complete Dimension History

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
       CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
       SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- Display Active Customer Report

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
       CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, SEGMENT
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

-- Point-in-Time Historical Query
  
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, HISTORICAL_MEMBERSHIP, SEGMENT,
       EFFECTIVE_DATE, EXPIRY_DATE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
  AND DATE '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

-- Metric Validation and Record Counts
   
SELECT 'TOTAL RECORD COUNT' AS METRIC, COUNT(*) AS VALUE
FROM DIM_CUSTOMER_HYBRID

UNION ALL

SELECT 'CURRENT RECORD COUNT', COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT 'HISTORICAL RECORD COUNT', COUNT(*)
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = FALSE;