
-- Create Database and Schema Context
CREATE WAREHOUSE IF NOT EXISTS BASIC_DM
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
USE WAREHOUSE BASIC_DM; 

CREATE DATABASE IF NOT EXISTS RETAIL_DW;
USE DATABASE RETAIL_DW;

CREATE SCHEMA IF NOT EXISTS SALES_ANALYTICS;
USE SCHEMA SALES_ANALYTICS;

SELECT CURRENT_DATABASE() AS "Current database",
       CURRENT_SCHEMA()   AS "Current schema";

CREATE OR REPLACE FILE FORMAT CSV_FF
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE RETAIL_STAGE
    FILE_FORMAT = CSV_FF;

-- Create Store Conformed Dimension Table (DIM_STORE)
  
CREATE OR REPLACE TABLE DIM_STORE (
    STORE_KEY      NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    STORE_ID       NUMBER,
    STORE_NAME     VARCHAR(100),
    CITY           VARCHAR(50),
    STATE          VARCHAR(50),
    STORE_MANAGER  VARCHAR(100)
);



-- Create Product Dimension Table (DIM_PRODUCT)

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY    NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    PRODUCT_ID     NUMBER,
    PRODUCT_NAME   VARCHAR(100),
    CATEGORY       VARCHAR(50),
    UNIT_PRICE     NUMBER(10,2)
);


-- Create Hybrid Customer Dimension Table (DIM_CUSTOMER_HYBRID)

CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY            NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    CUSTOMER_ID             NUMBER,
    CUSTOMER_NAME           VARCHAR(100),
    CITY                    VARCHAR(50),   -- current city, globally synced
    PREVIOUS_CITY           VARCHAR(50),   -- SCD Type 3
    STATE                   VARCHAR(50),
    CURRENT_MEMBERSHIP      VARCHAR(30),   -- SCD Type 6, globally synced
    PREVIOUS_MEMBERSHIP     VARCHAR(30),   -- SCD Type 6 / Type 3 column
    HISTORICAL_MEMBERSHIP   VARCHAR(30),   -- SCD Type 6 / Type 2 row slice
    SEGMENT                 VARCHAR(30),   -- SCD Type 2, row versioned
    EFFECTIVE_DATE          DATE,
    EXPIRY_DATE             DATE,
    IS_CURRENT              BOOLEAN
);


-- Populate Initial Store and Product Dimension Data

INSERT INTO DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, STORE_MANAGER)
SELECT $1, $2, $3, $4, $5
FROM @RETAIL_STAGE/stores.csv (FILE_FORMAT => 'CSV_FF');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE)
SELECT $1, $2, $3, $4
FROM @RETAIL_STAGE/products.csv (FILE_FORMAT => 'CSV_FF');


-- Populate Initial Customer Dimension Data

INSERT INTO DIM_CUSTOMER_HYBRID
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
     CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT,
     EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    $1, $2, $3, NULL, $4,
    $5, NULL, $5, $6,
    DATE '2026-01-01', DATE '9999-12-31', TRUE
FROM @RETAIL_STAGE/customers_initial.csv (FILE_FORMAT => 'CSV_FF');

-- Create Sales Transaction Fact Table (FACT_SALES)
-- Grain: one row per line item.

CREATE OR REPLACE TABLE FACT_SALES (
    SALES_KEY         NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    TRANSACTION_ID    VARCHAR(50),
    TRANSACTION_DATE  DATE,
    CUSTOMER_KEY       NUMBER,   -- FK -> DIM_CUSTOMER_HYBRID(CUSTOMER_KEY)
    STORE_KEY          NUMBER,   -- FK -> DIM_STORE(STORE_KEY)
    PRODUCT_KEY        NUMBER,   -- FK -> DIM_PRODUCT(PRODUCT_KEY)
    QUANTITY           NUMBER,
    UNIT_PRICE         NUMBER(10,2),
    TOTAL_AMOUNT       NUMBER(12,2)
);


-- Insert Q1 2026 Sales Fact Transactions
INSERT INTO FACT_SALES
    (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY,
     QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT
    'TXN-1001', DATE '2026-02-15',
    c.CUSTOMER_KEY, s.STORE_KEY, p.PRODUCT_KEY,
    1, p.UNIT_PRICE, 1 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c, DIM_STORE s, DIM_PRODUCT p
WHERE c.CUSTOMER_ID = 101 AND c.IS_CURRENT = TRUE
  AND s.STORE_ID = 201
  AND p.PRODUCT_ID = 501;

INSERT INTO FACT_SALES
    (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY,
     QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT
    'TXN-1002', DATE '2026-03-10',
    c.CUSTOMER_KEY, s.STORE_KEY, p.PRODUCT_KEY,
    2, p.UNIT_PRICE, 2 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c, DIM_STORE s, DIM_PRODUCT p
WHERE c.CUSTOMER_ID = 103 AND c.IS_CURRENT = TRUE
  AND s.STORE_ID = 203
  AND p.PRODUCT_ID = 502;


-- Apply Store Manager Update (SCD Type 1 Overwrite)

UPDATE DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;

SELECT STORE_ID, STORE_NAME, CITY, STATE, STORE_MANAGER
FROM DIM_STORE
WHERE STORE_ID = 201;

-- Execute Multi-Attribute Customer Updates
  
CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR(100),
    CITY            VARCHAR(50),
    STATE           VARCHAR(50),
    MEMBERSHIP      VARCHAR(30),
    SEGMENT         VARCHAR(30),
    EFFECTIVE_DATE  DATE
);

COPY INTO CUSTOMER_UPDATES (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT, EFFECTIVE_DATE)
FROM @RETAIL_STAGE/customer_updates.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';

-- Step 1: Expire active records (one statement per customer) 

UPDATE DIM_CUSTOMER_HYBRID d
SET d.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    d.IS_CURRENT  = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT  = TRUE
  AND d.CUSTOMER_ID = 101;

UPDATE DIM_CUSTOMER_HYBRID d
SET d.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    d.IS_CURRENT  = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT  = TRUE
  AND d.CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_HYBRID d
SET d.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    d.IS_CURRENT  = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT  = TRUE
  AND d.CUSTOMER_ID = 104;

-- Step 2: Insert new active row versions (single statement, 3 rows) 

INSERT INTO DIM_CUSTOMER_HYBRID
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
     CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
     SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    u.CUSTOMER_ID, u.CUSTOMER_NAME,
    u.CITY,
    old.CITY AS PREVIOUS_CITY,
    u.STATE,
    u.MEMBERSHIP AS CURRENT_MEMBERSHIP,
    old.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,
    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,
    u.SEGMENT,
    u.EFFECTIVE_DATE, DATE '9999-12-31', TRUE
FROM CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_HYBRID old
    ON old.CUSTOMER_ID = u.CUSTOMER_ID
   AND old.IS_CURRENT  = FALSE
   AND old.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE);

--  Step 3: Synchronize CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP,
--              CITY, STATE across ALL rows per changed customer 

UPDATE DIM_CUSTOMER_HYBRID d
SET d.CITY                = cur.CITY,
    d.STATE               = cur.STATE,
    d.CURRENT_MEMBERSHIP  = cur.CURRENT_MEMBERSHIP,
    d.PREVIOUS_MEMBERSHIP = cur.PREVIOUS_MEMBERSHIP
FROM (
    SELECT CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
    FROM DIM_CUSTOMER_HYBRID
    WHERE CUSTOMER_ID = 101 AND IS_CURRENT = TRUE
) cur
WHERE d.CUSTOMER_ID = 101;


UPDATE DIM_CUSTOMER_HYBRID d
SET d.CITY                = cur.CITY,
    d.STATE               = cur.STATE,
    d.CURRENT_MEMBERSHIP  = cur.CURRENT_MEMBERSHIP,
    d.PREVIOUS_MEMBERSHIP = cur.PREVIOUS_MEMBERSHIP
FROM (
    SELECT CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
    FROM DIM_CUSTOMER_HYBRID
    WHERE CUSTOMER_ID = 103 AND IS_CURRENT = TRUE
) cur
WHERE d.CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_HYBRID d
SET d.CITY                = cur.CITY,
    d.STATE               = cur.STATE,
    d.CURRENT_MEMBERSHIP  = cur.CURRENT_MEMBERSHIP,
    d.PREVIOUS_MEMBERSHIP = cur.PREVIOUS_MEMBERSHIP
FROM (
    SELECT CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
    FROM DIM_CUSTOMER_HYBRID
    WHERE CUSTOMER_ID = 104 AND IS_CURRENT = TRUE
) cur
WHERE d.CUSTOMER_ID = 104;


--  TASK 11 — Insert Q2 2026 Sales Transaction

INSERT INTO FACT_SALES
    (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY,
     QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT
    'TXN-2001', DATE '2026-04-15',
    c.CUSTOMER_KEY, s.STORE_KEY, p.PRODUCT_KEY,
    1, p.UNIT_PRICE, 1 * p.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID c, DIM_STORE s, DIM_PRODUCT p
WHERE c.CUSTOMER_ID = 101 AND c.IS_CURRENT = TRUE
  AND s.STORE_ID = 201
  AND p.PRODUCT_ID = 503;
-- Display Full Customer Dimension History
  
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY,
       CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
       SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- Point-in-Time Point-of-Sale Analytics Query
  
SELECT
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,
    c101.CUSTOMER_ID,
    c101.CUSTOMER_NAME,
    cur.CITY                        AS CURRENT_CITY,
    c101.HISTORICAL_MEMBERSHIP      AS MEMBERSHIP_AT_PURCHASE,
    c101.SEGMENT                    AS SEGMENT_AT_PURCHASE,
    s.STORE_NAME,
    p.PRODUCT_NAME,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
JOIN DIM_CUSTOMER_HYBRID c101
    ON f.TRANSACTION_DATE BETWEEN c101.EFFECTIVE_DATE AND c101.EXPIRY_DATE
   AND c101.CUSTOMER_ID = 101
JOIN DIM_CUSTOMER_HYBRID cur
    ON cur.CUSTOMER_ID = 101 AND cur.IS_CURRENT = TRUE
JOIN DIM_STORE s   ON f.STORE_KEY   = s.STORE_KEY
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
WHERE f.CUSTOMER_KEY IN (
    SELECT CUSTOMER_KEY FROM DIM_CUSTOMER_HYBRID WHERE CUSTOMER_ID = 101
)
ORDER BY f.TRANSACTION_DATE;

-- Warehouse Record Count and Data Auditing Validation
  
SELECT 'STORE DIMENSION RECORDS' AS METRIC, COUNT(*) AS VALUE FROM DIM_STORE

UNION ALL

SELECT 'PRODUCT DIMENSION RECORDS', COUNT(*) FROM DIM_PRODUCT

UNION ALL

SELECT 'TOTAL CUSTOMER DIMENSION RECORDS', COUNT(*) FROM DIM_CUSTOMER_HYBRID

UNION ALL

SELECT 'CURRENT CUSTOMER RECORDS', COUNT(*)
FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = TRUE

UNION ALL

SELECT 'HISTORICAL CUSTOMER RECORDS', COUNT(*)
FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = FALSE

UNION ALL

SELECT 'FACT SALES TRANSACTIONS', COUNT(*) FROM FACT_SALES;