-- Create Database and Schema Context
CREATE WAREHOUSE IF NOT EXISTS BASIC_DM
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
USE WAREHOUSE BASIC_DM; 

CREATE DATABASE IF NOT EXISTS RETAIL_SCHEMAS_DW;
USE DATABASE RETAIL_SCHEMAS_DW;

CREATE SCHEMA IF NOT EXISTS SCHEMA_COMPARISON;
USE SCHEMA SCHEMA_COMPARISON;

SELECT CURRENT_DATABASE() AS "Current database",
       CURRENT_SCHEMA()   AS "Current schema";

CREATE OR REPLACE FILE FORMAT CSV_FF
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE RETAIL_STAGE
    FILE_FORMAT = CSV_FF;
    
-- Create Denormalized Star Schema Store Dimension
CREATE OR REPLACE TABLE STAR_DIM_STORE (
    STORE_KEY        NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    STORE_ID         NUMBER,
    STORE_NAME       VARCHAR(100),
    CITY             VARCHAR(50),
    STATE            VARCHAR(50),
    REGION_NAME      VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);
-- Create Denormalized Star Schema Product Dimension
   
CREATE OR REPLACE TABLE STAR_DIM_PRODUCT (
    PRODUCT_KEY       NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    PRODUCT_ID        NUMBER,
    PRODUCT_NAME      VARCHAR(100),
    SUBCATEGORY_NAME  VARCHAR(50),
    CATEGORY_NAME     VARCHAR(50),
    UNIT_PRICE        NUMBER(10,2)
);

-- Load Star Schema Dimensions & Create Star Fact Table

INSERT INTO STAR_DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, REGION_NAME, REGIONAL_MANAGER)
SELECT $1, $2, $3, $4, $5, $6
FROM @RETAIL_STAGE/regions_and_stores.csv (FILE_FORMAT => 'CSV_FF');

INSERT INTO STAR_DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, SUBCATEGORY_NAME, CATEGORY_NAME, UNIT_PRICE)
SELECT $1, $2, $3, $4, $5
FROM @RETAIL_STAGE/product_hierarchy.csv (FILE_FORMAT => 'CSV_FF');

CREATE OR REPLACE TABLE STAR_FACT_SALES (
    SALES_KEY         NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    TRANSACTION_ID    VARCHAR(50),
    TRANSACTION_DATE  DATE,
    CUSTOMER_ID       NUMBER,
    STORE_KEY         NUMBER,   -- FK -> STAR_DIM_STORE
    PRODUCT_KEY       NUMBER,   -- FK -> STAR_DIM_PRODUCT
    QUANTITY          NUMBER,
    TOTAL_AMOUNT      NUMBER(12,2)
);

-- Load Star Schema Fact Data

CREATE OR REPLACE TABLE STG_SALES_TRANSACTIONS (
    TRANSACTION_ID    VARCHAR(50),
    TRANSACTION_DATE  DATE,
    CUSTOMER_ID       NUMBER,
    STORE_ID          NUMBER,
    PRODUCT_ID        NUMBER,
    QUANTITY          NUMBER,
    UNIT_PRICE        NUMBER(10,2)
);

COPY INTO STG_SALES_TRANSACTIONS
FROM @RETAIL_STAGE/sales_transactions.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';

INSERT INTO STAR_FACT_SALES
    (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_ID, STORE_KEY, PRODUCT_KEY, QUANTITY, TOTAL_AMOUNT)
SELECT
    t.TRANSACTION_ID, t.TRANSACTION_DATE, t.CUSTOMER_ID,
    s.STORE_KEY, p.PRODUCT_KEY,
    t.QUANTITY, t.QUANTITY * t.UNIT_PRICE
FROM STG_SALES_TRANSACTIONS t
JOIN STAR_DIM_STORE   s ON t.STORE_ID   = s.STORE_ID
JOIN STAR_DIM_PRODUCT p ON t.PRODUCT_ID = p.PRODUCT_ID;
-- Build Normalized Snowflake Schema Store Hierarchy
  
CREATE OR REPLACE TABLE SNOW_DIM_REGION (
    REGION_KEY        NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    REGION_NAME       VARCHAR(50),
    REGIONAL_MANAGER  VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOW_DIM_STORE (
    STORE_KEY   NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    STORE_ID    NUMBER,
    STORE_NAME  VARCHAR(100),
    CITY        VARCHAR(50),
    STATE       VARCHAR(50),
    REGION_KEY  NUMBER   -- FK -> SNOW_DIM_REGION
);

-- Build Normalized Snowflake Schema Product Hierarchy

CREATE OR REPLACE TABLE SNOW_DIM_CATEGORY (
    CATEGORY_KEY   NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    CATEGORY_NAME  VARCHAR(50)
);

CREATE OR REPLACE TABLE SNOW_DIM_SUBCATEGORY (
    SUBCATEGORY_KEY   NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    SUBCATEGORY_NAME  VARCHAR(50),
    CATEGORY_KEY      NUMBER   -- FK -> SNOW_DIM_CATEGORY
);

CREATE OR REPLACE TABLE SNOW_DIM_PRODUCT (
    PRODUCT_KEY       NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    PRODUCT_ID        NUMBER,
    PRODUCT_NAME      VARCHAR(100),
    UNIT_PRICE        NUMBER(10,2),
    SUBCATEGORY_KEY   NUMBER   -- FK -> SNOW_DIM_SUBCATEGORY
);
-- Populate Snowflake Schema Normalized Dimensions

-- Regions (distinct region_name + regional_manager pairs)
INSERT INTO SNOW_DIM_REGION (REGION_NAME, REGIONAL_MANAGER)
SELECT DISTINCT $5, $6
FROM @RETAIL_STAGE/regions_and_stores.csv (FILE_FORMAT => 'CSV_FF');

-- Stores, resolving REGION_KEY via region name
INSERT INTO SNOW_DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, REGION_KEY)
SELECT stg.$1, stg.$2, stg.$3, stg.$4, r.REGION_KEY
FROM @RETAIL_STAGE/regions_and_stores.csv (FILE_FORMAT => 'CSV_FF') stg
JOIN SNOW_DIM_REGION r ON stg.$5 = r.REGION_NAME;

-- Categories (distinct)
INSERT INTO SNOW_DIM_CATEGORY (CATEGORY_NAME)
SELECT DISTINCT $4
FROM @RETAIL_STAGE/product_hierarchy.csv (FILE_FORMAT => 'CSV_FF');

-- Subcategories (distinct), resolving CATEGORY_KEY
INSERT INTO SNOW_DIM_SUBCATEGORY (SUBCATEGORY_NAME, CATEGORY_KEY)
SELECT DISTINCT stg.$3, c.CATEGORY_KEY
FROM @RETAIL_STAGE/product_hierarchy.csv (FILE_FORMAT => 'CSV_FF') stg
JOIN SNOW_DIM_CATEGORY c ON stg.$4 = c.CATEGORY_NAME;

-- Products, resolving SUBCATEGORY_KEY
INSERT INTO SNOW_DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, SUBCATEGORY_KEY)
SELECT stg.$1, stg.$2, stg.$5, sc.SUBCATEGORY_KEY
FROM @RETAIL_STAGE/product_hierarchy.csv (FILE_FORMAT => 'CSV_FF') stg
JOIN SNOW_DIM_SUBCATEGORY sc ON stg.$3 = sc.SUBCATEGORY_NAME;

-- Create Snowflake Schema Fact Table & Load Data

CREATE OR REPLACE TABLE SNOW_FACT_SALES (
    SALES_KEY         NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    TRANSACTION_ID    VARCHAR(50),
    TRANSACTION_DATE  DATE,
    CUSTOMER_ID       NUMBER,
    STORE_KEY         NUMBER,   -- FK -> SNOW_DIM_STORE
    PRODUCT_KEY       NUMBER,   -- FK -> SNOW_DIM_PRODUCT
    QUANTITY          NUMBER,
    TOTAL_AMOUNT      NUMBER(12,2)
);
-- Table SNOW_FACT_SALES successfully created.

INSERT INTO SNOW_FACT_SALES
    (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_ID, STORE_KEY, PRODUCT_KEY, QUANTITY, TOTAL_AMOUNT)
SELECT
    t.TRANSACTION_ID, t.TRANSACTION_DATE, t.CUSTOMER_ID,
    s.STORE_KEY, p.PRODUCT_KEY,
    t.QUANTITY, t.QUANTITY * t.UNIT_PRICE
FROM STG_SALES_TRANSACTIONS t
JOIN SNOW_DIM_STORE   s ON t.STORE_ID   = s.STORE_ID
JOIN SNOW_DIM_PRODUCT p ON t.PRODUCT_ID = p.PRODUCT_ID;

-- Star Schema Analytics Query (Single-Hop Join)

SELECT
    s.REGION_NAME,
    p.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE   s ON f.STORE_KEY   = s.STORE_KEY
JOIN STAR_DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
GROUP BY s.REGION_NAME, p.CATEGORY_NAME
ORDER BY s.REGION_NAME, p.CATEGORY_NAME;

-- Snowflake Schema Analytics Query (Multi-Hop Join)

SELECT
    r.REGION_NAME,
    c.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES f
JOIN SNOW_DIM_STORE       st ON f.STORE_KEY        = st.STORE_KEY
JOIN SNOW_DIM_REGION      r  ON st.REGION_KEY       = r.REGION_KEY
JOIN SNOW_DIM_PRODUCT     p  ON f.PRODUCT_KEY       = p.PRODUCT_KEY
JOIN SNOW_DIM_SUBCATEGORY sc ON p.SUBCATEGORY_KEY   = sc.SUBCATEGORY_KEY
JOIN SNOW_DIM_CATEGORY    c  ON sc.CATEGORY_KEY     = c.CATEGORY_KEY
GROUP BY r.REGION_NAME, c.CATEGORY_NAME
ORDER BY r.REGION_NAME, c.CATEGORY_NAME;

-- Architectural Analysis: Compare Star vs. Snowflake

SELECT * FROM (
    SELECT 'Dimension Normalization Level' AS "METRIC / FEATURE",
           'Denormalized (Flat)'            AS "STAR SCHEMA",
           'Normalized (Hierarchical)'      AS "SNOWFLAKE SCHEMA"
    UNION ALL
    SELECT 'Total Dimension Tables', '2 Tables', '5 Tables'
    UNION ALL
    SELECT 'Joins for Category Revenue', '2 Joins (Fact + 2 Dims)', '5 Joins (Fact + 5 Dims)'
    UNION ALL
    SELECT 'Data Redundancy', 'Higher (Repeated text)', 'Lower (Normalized IDs)'
    UNION ALL
    SELECT 'Query Simplicity', 'High (Simple GROUP BY)', 'Lower (Requires nested FKs)'
);

-- Regional Manager Sales Performance Report

SELECT
    s.REGIONAL_MANAGER,
    SUM(f.QUANTITY)      AS TOTAL_ITEMS_SOLD,
    SUM(f.TOTAL_AMOUNT)  AS TOTAL_SALES_AMOUNT
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE s ON f.STORE_KEY = s.STORE_KEY
GROUP BY s.REGIONAL_MANAGER
ORDER BY s.REGIONAL_MANAGER;

-- Full Warehouse Architecture Audit & Record Count

SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_STORE' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM STAR_DIM_STORE
UNION ALL
SELECT 'Star Schema', 'STAR_DIM_PRODUCT', COUNT(*) FROM STAR_DIM_PRODUCT
UNION ALL
SELECT 'Star Schema', 'STAR_FACT_SALES', COUNT(*) FROM STAR_FACT_SALES
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_REGION', COUNT(*) FROM SNOW_DIM_REGION
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_STORE', COUNT(*) FROM SNOW_DIM_STORE
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_CATEGORY', COUNT(*) FROM SNOW_DIM_CATEGORY
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_SUBCATEGORY', COUNT(*) FROM SNOW_DIM_SUBCATEGORY
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_PRODUCT', COUNT(*) FROM SNOW_DIM_PRODUCT
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_FACT_SALES', COUNT(*) FROM SNOW_FACT_SALES;
