-- Create Environment Context
CREATE WAREHOUSE IF NOT EXISTS BASIC_DM
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
USE WAREHOUSE BASIC_DM;

CREATE DATABASE IF NOT EXISTS HEALTHCARE_DW;
USE DATABASE HEALTHCARE_DW;

CREATE SCHEMA IF NOT EXISTS SCHEMA_COMPARE_LAB;
USE SCHEMA SCHEMA_COMPARE_LAB;

SELECT CURRENT_DATABASE() AS "Current database",
       CURRENT_SCHEMA()   AS "Current schema";

CREATE OR REPLACE FILE FORMAT CSV_FF
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE HEALTHCARE_STAGE
    FILE_FORMAT = CSV_FF;


-- Build Star Schema Denormalized Hospital Dimension

CREATE OR REPLACE TABLE STAR_DIM_HOSPITAL (
    HOSPITAL_KEY      NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    HOSPITAL_ID       NUMBER,
    HOSPITAL_NAME     VARCHAR(100),
    CITY              VARCHAR(50),
    STATE             VARCHAR(50),
    NETWORK_NAME      VARCHAR(100),
    NETWORK_DIRECTOR  VARCHAR(100)
);
-- Build Star Schema Denormalized Treatment Dimension
  
CREATE OR REPLACE TABLE STAR_DIM_TREATMENT (
    TREATMENT_KEY         NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    TREATMENT_ID          NUMBER,
    TREATMENT_NAME        VARCHAR(100),
    DIAGNOSIS_GROUP_NAME  VARCHAR(50),
    STANDARD_COST         NUMBER(12,2)
);
-- Load Star Schema Dimension Data
  
INSERT INTO STAR_DIM_HOSPITAL (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, NETWORK_NAME, NETWORK_DIRECTOR)
SELECT $1, $2, $3, $4, $6, $7
FROM @HEALTHCARE_STAGE/hospital_hierarchy.csv (FILE_FORMAT => 'CSV_FF');

INSERT INTO STAR_DIM_TREATMENT (TREATMENT_ID, TREATMENT_NAME, DIAGNOSIS_GROUP_NAME, STANDARD_COST)
SELECT $1, $2, $4, $5
FROM @HEALTHCARE_STAGE/treatment_hierarchy.csv (FILE_FORMAT => 'CSV_FF');

-- Build & Load Star Schema Claims Fact Table

CREATE OR REPLACE TABLE STAR_FACT_CLAIMS (
    CLAIM_KEY        NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    CLAIM_ID         VARCHAR(50),
    CLAIM_DATE       DATE,
    PATIENT_ID       NUMBER,
    HOSPITAL_KEY     NUMBER,   -- FK -> STAR_DIM_HOSPITAL
    TREATMENT_KEY    NUMBER,   -- FK -> STAR_DIM_TREATMENT
    CLAIMED_AMOUNT   NUMBER(12,2),
    APPROVED_AMOUNT  NUMBER(12,2)
);


CREATE OR REPLACE TABLE STG_INSURANCE_CLAIMS (
    CLAIM_ID         VARCHAR(50),
    CLAIM_DATE       DATE,
    PATIENT_ID       NUMBER,
    HOSPITAL_ID      NUMBER,
    TREATMENT_ID     NUMBER,
    CLAIMED_AMOUNT   NUMBER(12,2),
    APPROVED_AMOUNT  NUMBER(12,2)
);

COPY INTO STG_INSURANCE_CLAIMS
FROM @HEALTHCARE_STAGE/insurance_claims.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';

INSERT INTO STAR_FACT_CLAIMS
    (CLAIM_ID, CLAIM_DATE, PATIENT_ID, HOSPITAL_KEY, TREATMENT_KEY, CLAIMED_AMOUNT, APPROVED_AMOUNT)
SELECT
    c.CLAIM_ID, c.CLAIM_DATE, c.PATIENT_ID,
    h.HOSPITAL_KEY, t.TREATMENT_KEY,
    c.CLAIMED_AMOUNT, c.APPROVED_AMOUNT
FROM STG_INSURANCE_CLAIMS c
JOIN STAR_DIM_HOSPITAL  h ON c.HOSPITAL_ID  = h.HOSPITAL_ID
JOIN STAR_DIM_TREATMENT t ON c.TREATMENT_ID = t.TREATMENT_ID;

-- Build Normalized Snowflake Schema Hospital Hierarchy

CREATE OR REPLACE TABLE SNOW_DIM_NETWORK (
    NETWORK_KEY       NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    NETWORK_ID        NUMBER,
    NETWORK_NAME      VARCHAR(100),
    NETWORK_DIRECTOR  VARCHAR(100)
);

CREATE OR REPLACE TABLE SNOW_DIM_HOSPITAL (
    HOSPITAL_KEY   NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    HOSPITAL_ID    NUMBER,
    HOSPITAL_NAME  VARCHAR(100),
    CITY           VARCHAR(50),
    STATE          VARCHAR(50),
    NETWORK_KEY    NUMBER   -- FK -> SNOW_DIM_NETWORK
);

-- Build Normalized Snowflake Schema Treatment Hierarchy

CREATE OR REPLACE TABLE SNOW_DIM_DIAGNOSIS_GROUP (
    DIAGNOSIS_GROUP_KEY   NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    DIAGNOSIS_GROUP_ID    VARCHAR(20),
    DIAGNOSIS_GROUP_NAME  VARCHAR(50)
);

CREATE OR REPLACE TABLE SNOW_DIM_TREATMENT (
    TREATMENT_KEY        NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    TREATMENT_ID         NUMBER,
    TREATMENT_NAME        VARCHAR(100),
    STANDARD_COST         NUMBER(12,2),
    DIAGNOSIS_GROUP_KEY   NUMBER   -- FK -> SNOW_DIM_DIAGNOSIS_GROUP
);

-- Populate Snowflake Schema Normalized Hierarchies

-- Networks (distinct)
INSERT INTO SNOW_DIM_NETWORK (NETWORK_ID, NETWORK_NAME, NETWORK_DIRECTOR)
SELECT DISTINCT $5, $6, $7
FROM @HEALTHCARE_STAGE/hospital_hierarchy.csv (FILE_FORMAT => 'CSV_FF');

-- Hospitals, resolving NETWORK_KEY
INSERT INTO SNOW_DIM_HOSPITAL (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, NETWORK_KEY)
SELECT stg.$1, stg.$2, stg.$3, stg.$4, n.NETWORK_KEY
FROM @HEALTHCARE_STAGE/hospital_hierarchy.csv (FILE_FORMAT => 'CSV_FF') stg
JOIN SNOW_DIM_NETWORK n ON stg.$5 = n.NETWORK_ID;

-- Diagnosis groups (distinct)
INSERT INTO SNOW_DIM_DIAGNOSIS_GROUP (DIAGNOSIS_GROUP_ID, DIAGNOSIS_GROUP_NAME)
SELECT DISTINCT $3, $4
FROM @HEALTHCARE_STAGE/treatment_hierarchy.csv (FILE_FORMAT => 'CSV_FF');

-- Treatments, resolving DIAGNOSIS_GROUP_KEY
INSERT INTO SNOW_DIM_TREATMENT (TREATMENT_ID, TREATMENT_NAME, STANDARD_COST, DIAGNOSIS_GROUP_KEY)
SELECT stg.$1, stg.$2, stg.$5, dg.DIAGNOSIS_GROUP_KEY
FROM @HEALTHCARE_STAGE/treatment_hierarchy.csv (FILE_FORMAT => 'CSV_FF') stg
JOIN SNOW_DIM_DIAGNOSIS_GROUP dg ON stg.$3 = dg.DIAGNOSIS_GROUP_ID;

-- Build & Load Snowflake Schema Claims Fact Table

CREATE OR REPLACE TABLE SNOW_FACT_CLAIMS (
    CLAIM_KEY        NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    CLAIM_ID         VARCHAR(50),
    CLAIM_DATE       DATE,
    PATIENT_ID       NUMBER,
    HOSPITAL_KEY     NUMBER,   -- FK -> SNOW_DIM_HOSPITAL
    TREATMENT_KEY    NUMBER,   -- FK -> SNOW_DIM_TREATMENT
    CLAIMED_AMOUNT   NUMBER(12,2),
    APPROVED_AMOUNT  NUMBER(12,2)
);

INSERT INTO SNOW_FACT_CLAIMS
    (CLAIM_ID, CLAIM_DATE, PATIENT_ID, HOSPITAL_KEY, TREATMENT_KEY, CLAIMED_AMOUNT, APPROVED_AMOUNT)
SELECT
    c.CLAIM_ID, c.CLAIM_DATE, c.PATIENT_ID,
    h.HOSPITAL_KEY, t.TREATMENT_KEY,
    c.CLAIMED_AMOUNT, c.APPROVED_AMOUNT
FROM STG_INSURANCE_CLAIMS c
JOIN SNOW_DIM_HOSPITAL  h ON c.HOSPITAL_ID  = h.HOSPITAL_ID
JOIN SNOW_DIM_TREATMENT t ON c.TREATMENT_ID = t.TREATMENT_ID;


-- Star Schema Specialty Claims Analysis (Flat 1-Hop Query)

SELECT
    t.DIAGNOSIS_GROUP_NAME,
    SUM(f.CLAIMED_AMOUNT)  AS TOTAL_CLAIMED_AMOUNT,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS f
JOIN STAR_DIM_TREATMENT t ON f.TREATMENT_KEY = t.TREATMENT_KEY
GROUP BY t.DIAGNOSIS_GROUP_NAME
ORDER BY t.DIAGNOSIS_GROUP_NAME;

SELECT
    t.DIAGNOSIS_GROUP_NAME,
    SUM(f.CLAIMED_AMOUNT)  AS TOTAL_CLAIMED_AMOUNT,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS f
JOIN STAR_DIM_TREATMENT t ON f.TREATMENT_KEY = t.TREATMENT_KEY
GROUP BY t.DIAGNOSIS_GROUP_NAME
ORDER BY t.DIAGNOSIS_GROUP_NAME;

-- Snowflake Schema Specialty Claims Analysis (Multi-Hop)
  
SELECT
    dg.DIAGNOSIS_GROUP_NAME,
    SUM(f.CLAIMED_AMOUNT)  AS TOTAL_CLAIMED_AMOUNT,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS f
JOIN SNOW_DIM_TREATMENT        t  ON f.TREATMENT_KEY       = t.TREATMENT_KEY
JOIN SNOW_DIM_DIAGNOSIS_GROUP  dg ON t.DIAGNOSIS_GROUP_KEY  = dg.DIAGNOSIS_GROUP_KEY
GROUP BY dg.DIAGNOSIS_GROUP_NAME
ORDER BY dg.DIAGNOSIS_GROUP_NAME;

-- Hospital Network Director Performance Report

SELECT
    h.NETWORK_DIRECTOR,
    COUNT(*)                AS TOTAL_CLAIMS_HANDLED,
    SUM(f.APPROVED_AMOUNT)  AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS f
JOIN STAR_DIM_HOSPITAL h ON f.HOSPITAL_KEY = h.HOSPITAL_KEY
GROUP BY h.NETWORK_DIRECTOR
ORDER BY TOTAL_CLAIMS_HANDLED DESC;


-- Data Anomaly Analysis: Master Data Update Test

UPDATE STAR_DIM_HOSPITAL
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_NAME = 'Apollo Healthcare Group';
-- number of rows updated: 2

-- Snowflake Schema: the director's name is stored once per network,
-- so a single row update propagates automatically through the FK.
UPDATE SNOW_DIM_NETWORK
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_ID = 10;
-- number of rows updated: 1

SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_HOSPITAL' AS UPDATED_TABLE,
       2 AS ROWS_UPDATED, 'Higher (Multiple rows)' AS MAINTENANCE_EFFORT
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_NETWORK',
       1, 'Lower (Single row)';


-- Full Architecture Record Audit & Schema Comparison

SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_HOSPITAL' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM STAR_DIM_HOSPITAL
UNION ALL
SELECT 'Star Schema', 'STAR_DIM_TREATMENT', COUNT(*) FROM STAR_DIM_TREATMENT
UNION ALL
SELECT 'Star Schema', 'STAR_FACT_CLAIMS', COUNT(*) FROM STAR_FACT_CLAIMS
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_NETWORK', COUNT(*) FROM SNOW_DIM_NETWORK
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_HOSPITAL', COUNT(*) FROM SNOW_DIM_HOSPITAL
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_DIAGNOSIS_GROUP', COUNT(*) FROM SNOW_DIM_DIAGNOSIS_GROUP
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_TREATMENT', COUNT(*) FROM SNOW_DIM_TREATMENT
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_FACT_CLAIMS', COUNT(*) FROM SNOW_FACT_CLAIMS;