CREATE WAREHOUSE IF NOT EXISTS PROJECT14_B_WH
WITH WAREHOUSE_SIZE = 'MEDIUM'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE PROJECT14_B_WH;
CREATE DATABASE IF NOT EXISTS PAYMENT_GATEWAY_DW;
USE DATABASE PAYMENT_GATEWAY_DW;

CREATE SCHEMA IF NOT EXISTS MEDALLION_LAKEHOUSE;
USE SCHEMA MEDALLION_LAKEHOUSE;

CREATE OR REPLACE FILE FORMAT JSON_FF
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = FALSE   -- each line is its own JSON object (NDJSON)
    STRIP_NULL_VALUES = FALSE;

CREATE OR REPLACE STAGE PAYMENTS_STAGE
    FILE_FORMAT = JSON_FF;

LIST @PAYMENTS_STAGE;

-- Bronze Layer Setup & Ingestion
CREATE OR REPLACE TABLE BRONZE_PAYMENT_PAYLOADS (
    BRONZE_ID   NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    TXN_JSON    VARIANT,
    LOADED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO BRONZE_PAYMENT_PAYLOADS (TXN_JSON)
FROM (
    SELECT $1
    FROM @PAYMENTS_STAGE
)
PATTERN = '.*\.json'
FILE_FORMAT = (FORMAT_NAME = JSON_FF)
ON_ERROR = 'ABORT_STATEMENT';
-- number of rows loaded: 8

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS_CT
FROM BRONZE_PAYMENT_PAYLOADS;

-- Silver Layer ETL & Fee Computations
CREATE OR REPLACE TABLE SILVER_CLEANED_TRANSACTIONS (
    SILVER_KEY              NUMBER AUTOINCREMENT START 1 INCREMENT 1 PRIMARY KEY,
    TXN_ID                  VARCHAR(50),
    TXN_TIME                TIMESTAMP_NTZ,
    MERCHANT_ID              NUMBER,
    MERCHANT_NAME            VARCHAR(100),
    MASKED_CARD              VARCHAR(30),
    GROSS_AMOUNT             NUMBER(12,2),
    FEE_PCT                  NUMBER(5,2),
    PROCESSING_FEE           NUMBER(12,2),
    NET_SETTLEMENT_AMOUNT    NUMBER(12,2),
    STATUS                   VARCHAR(20)
);

INSERT INTO SILVER_CLEANED_TRANSACTIONS
    (TXN_ID, TXN_TIME, MERCHANT_ID, MERCHANT_NAME, MASKED_CARD,
     GROSS_AMOUNT, FEE_PCT, PROCESSING_FEE, NET_SETTLEMENT_AMOUNT, STATUS)
SELECT
    TXN_JSON:txn_id::VARCHAR,
    TO_TIMESTAMP_NTZ(TXN_JSON:txn_time::VARCHAR),
    TXN_JSON:merchant_id::NUMBER,
    TXN_JSON:merchant_name::VARCHAR,
    'XXXX-XXXX-XXXX-' || RIGHT(TXN_JSON:card_number::VARCHAR, 4) AS MASKED_CARD,
    TXN_JSON:amount::NUMBER(12,2)                                 AS GROSS_AMOUNT,
    TXN_JSON:fee_pct::NUMBER(5,2)                                 AS FEE_PCT,
    ROUND(TXN_JSON:amount::NUMBER(12,2) * (TXN_JSON:fee_pct::NUMBER(5,2) / 100), 2) AS PROCESSING_FEE,
    ROUND(TXN_JSON:amount::NUMBER(12,2)
          - (TXN_JSON:amount::NUMBER(12,2) * (TXN_JSON:fee_pct::NUMBER(5,2) / 100)), 2) AS NET_SETTLEMENT_AMOUNT,
    TXN_JSON:status::VARCHAR
FROM BRONZE_PAYMENT_PAYLOADS;
-- number of rows inserted: 8

SELECT TXN_ID, MERCHANT_ID, MERCHANT_NAME, MASKED_CARD, GROSS_AMOUNT,
       PROCESSING_FEE, NET_SETTLEMENT_AMOUNT, STATUS
FROM SILVER_CLEANED_TRANSACTIONS
ORDER BY TXN_ID;

-- Gold Layer Financial Aggregations
CREATE OR REPLACE TABLE GOLD_MERCHANT_SETTLEMENTS (
    MERCHANT_ID            NUMBER,
    MERCHANT_NAME           VARCHAR(100),
    TOTAL_APPROVED_GROSS    NUMBER(14,2),
    TOTAL_GATEWAY_FEES      NUMBER(14,2),
    TOTAL_NET_PAYOUT        NUMBER(14,2),
    APPROVED_COUNT          NUMBER
);

INSERT INTO GOLD_MERCHANT_SETTLEMENTS
SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    SUM(GROSS_AMOUNT)          AS TOTAL_APPROVED_GROSS,
    SUM(PROCESSING_FEE)        AS TOTAL_GATEWAY_FEES,
    SUM(NET_SETTLEMENT_AMOUNT) AS TOTAL_NET_PAYOUT,
    COUNT(*)                   AS APPROVED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY MERCHANT_ID, MERCHANT_NAME;

SELECT * FROM GOLD_MERCHANT_SETTLEMENTS
ORDER BY MERCHANT_ID;

-- Data Corruption Simulation & Time-Travel Inspection
SET pre_corruption_ts = (SELECT CURRENT_TIMESTAMP());

UPDATE SILVER_CLEANED_TRANSACTIONS
SET STATUS = 'REFUNDED'
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED';

SELECT TXN_ID, MERCHANT_NAME, GROSS_AMOUNT, STATUS
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
ORDER BY TXN_ID;

SELECT TXN_ID, MERCHANT_NAME, GROSS_AMOUNT, STATUS
FROM SILVER_CLEANED_TRANSACTIONS
    AT (TIMESTAMP => $pre_corruption_ts)
WHERE MERCHANT_NAME = 'TechZone'
ORDER BY TXN_ID;

-- Time-Travel Recovery Execution
UPDATE SILVER_CLEANED_TRANSACTIONS live
SET live.STATUS = snap.STATUS
FROM (
    SELECT TXN_ID, STATUS
    FROM SILVER_CLEANED_TRANSACTIONS AT (TIMESTAMP => $pre_corruption_ts)
    WHERE MERCHANT_NAME = 'TechZone'
) snap
WHERE live.TXN_ID = snap.TXN_ID
  AND live.STATUS = 'REFUNDED';

SELECT
    MERCHANT_NAME,
    SUM(IFF(STATUS = 'APPROVED', 1, 0)) AS APPROVED_COUNT,
    SUM(IFF(STATUS = 'REFUNDED', 1, 0)) AS REFUNDED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
GROUP BY MERCHANT_NAME;

-- End-to-End Pipeline Reconciliation Audit
WITH bronze_totals AS (
    SELECT SUM(TXN_JSON:amount::NUMBER(12,2)) AS BRONZE_GROSS_SUM
    FROM BRONZE_PAYMENT_PAYLOADS
),
silver_totals AS (
    SELECT SUM(GROSS_AMOUNT) AS SILVER_GROSS_SUM
    FROM SILVER_CLEANED_TRANSACTIONS
),
gold_totals AS (
    SELECT SUM(TOTAL_APPROVED_GROSS) AS GOLD_GROSS_SUM
    FROM GOLD_MERCHANT_SETTLEMENTS
)
SELECT
    b.BRONZE_GROSS_SUM,
    s.SILVER_GROSS_SUM,
    g.GOLD_GROSS_SUM,
    (b.BRONZE_GROSS_SUM = s.SILVER_GROSS_SUM) AS DATA_MATCH_FLAG
FROM bronze_totals b, silver_totals s, gold_totals g;
