--Phase 1
CREATE OR REPLACE WAREHOUSE RETAIL_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE RETAIL_DB;

CREATE OR REPLACE SCHEMA RETAIL_DB.SALES_SCHEMA;

USE DATABASE RETAIL_DB;

USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE SALES_STAGE
FILE_FORMAT = CSV_FORMAT;

SHOW WAREHOUSES;
SHOW DATABASES;
SHOW SCHEMAS;
SHOW FILE FORMATS;
SHOW STAGES;

LIST @SALES_STAGE;

--Phase 2
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID INT,
    CUSTOMER_NAME STRING,
    CITY STRING,
    MEMBERSHIP STRING
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID INT,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID INT,
    BRANCH_NAME STRING,
    CITY STRING
);

CREATE OR REPLACE TABLE SALES (
    SALE_ID INT,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    QUANTITY INT,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2)
);

SHOW TABLES;

COPY INTO CUSTOMERS
FROM @SALES_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO PRODUCTS
FROM @SALES_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO BRANCHES
FROM @SALES_STAGE/branches.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO SALES
FROM @SALES_STAGE/sales.csv
FILE_FORMAT = CSV_FORMAT;

SELECT *
FROM CUSTOMERS;

SELECT *
FROM PRODUCTS;

SELECT *
FROM BRANCHES;

SELECT *
FROM SALES;

-- Phase 3
SELECT
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
INNER JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC;

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES
FROM BRANCHES B
INNER JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_SALES DESC;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
INNER JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    P.CATEGORY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
INNER JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
INNER JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
INNER JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 1;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
INNER JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 3;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
INNER JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 3;

-- Phase 4
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM CUSTOMERS C
INNER JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS BRANCH_RANK
FROM BRANCHES B
INNER JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY BRANCH_RANK;

WITH PRODUCT_REVENUE AS (
    SELECT
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM PRODUCTS P
    INNER JOIN SALES S
        ON P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY
),

RANKED_PRODUCTS AS (
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        TOTAL_REVENUE,
        ROW_NUMBER() OVER (
            PARTITION BY CATEGORY
            ORDER BY TOTAL_REVENUE DESC
        ) AS PRODUCT_RANK
    FROM PRODUCT_REVENUE
)

SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    TOTAL_REVENUE
FROM RANKED_PRODUCTS
WHERE PRODUCT_RANK = 1;

SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (
        ORDER BY SALE_DATE, SALE_ID
    ) AS CUMULATIVE_SALES
FROM SALES
ORDER BY SALE_DATE, SALE_ID;

SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    AVG(TOTAL_AMOUNT) OVER () AS AVERAGE_SALE_AMOUNT
FROM SALES
ORDER BY SALE_DATE, SALE_ID;

WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM CUSTOMERS C
    INNER JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
)

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_REVENUE
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

-- Phase 5
WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENT
    FROM CUSTOMERS C
    INNER JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
),

AVERAGE_SPENDING AS (
    SELECT
        AVG(TOTAL_SPENT) AS AVG_SPENDING
    FROM CUSTOMER_REVENUE
)

SELECT
    CR.CUSTOMER_ID,
    CR.CUSTOMER_NAME,
    CR.TOTAL_SPENT,
    A.AVG_SPENDING
FROM CUSTOMER_REVENUE CR
CROSS JOIN AVERAGE_SPENDING A
WHERE CR.TOTAL_SPENT > A.AVG_SPENDING
ORDER BY CR.TOTAL_SPENT DESC;

-- Phase 6
-- CREATE SALES_REPORT VIEW

CREATE OR REPLACE VIEW SALES_REPORT AS
SELECT
    S.SALE_ID,
    C.CUSTOMER_NAME,
    P.PRODUCT_NAME,
    P.CATEGORY,
    B.BRANCH_NAME,
    S.QUANTITY,
    S.SALE_DATE,
    S.TOTAL_AMOUNT
FROM SALES S
INNER JOIN CUSTOMERS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
INNER JOIN PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN BRANCHES B
    ON S.BRANCH_ID = B.BRANCH_ID;

-- VERIFY SALES_REPORT VIEW

SHOW VIEWS;

DESC VIEW SALES_REPORT;


-- QUERY SALES_REPORT

SELECT *
FROM SALES_REPORT
ORDER BY SALE_DATE, SALE_ID;


-- CREATE TOP_CUSTOMERS
-- MATERIALIZED VIEW

CREATE OR REPLACE MATERIALIZED VIEW TOP_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    SUM(TOTAL_AMOUNT) AS TOTAL_SPENT
FROM SALES
GROUP BY CUSTOMER_ID;

-- VERIFY MATERIALIZED VIEW

SHOW MATERIALIZED VIEWS;

DESC MATERIALIZED VIEW TOP_CUSTOMERS;

-- QUERY TOP_CUSTOMERS
SELECT
    T.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    T.TOTAL_SPENT
FROM TOP_CUSTOMERS T
INNER JOIN CUSTOMERS C
    ON T.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY T.TOTAL_SPENT DESC;

-- TOP THREE CUSTOMERS

SELECT *
FROM TOP_CUSTOMERS
ORDER BY TOTAL_SPENT DESC
LIMIT 3;