-- Phase 1
CREATE OR REPLACE WAREHOUSE ENTERPRISE_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE ENTERPRISE_DB;

CREATE OR REPLACE SCHEMA ENTERPRISE_DB.SALES_SCHEMA;

USE DATABASE ENTERPRISE_DB;

USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE SALES_STAGE
FILE_FORMAT = CSV_FORMAT;

SHOW WAREHOUSES;
SHOW DATABASES;
SHOW SCHEMAS;
SHOW FILE FORMATS;
SHOW STAGES;

LIST @SALES_STAGE;

-- Phase 2
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID INT,
    CUSTOMER_NAME STRING,
    CITY STRING,
    MEMBERSHIP STRING
);


CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID INT,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER(10,2)
);


CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID INT,
    BRANCH_NAME STRING,
    STATE STRING
);

CREATE OR REPLACE TABLE SALES (
    SALE_ID INT,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    QUANTITY INT,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2)
);


SHOW TABLES;


COPY INTO CUSTOMERS
FROM @SALES_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT;


COPY INTO PRODUCTS
FROM @SALES_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT;


COPY INTO BRANCHES
FROM @SALES_STAGE/branches.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO SALES
FROM @SALES_STAGE/sales_history.csv
FILE_FORMAT = CSV_FORMAT;

SELECT *
FROM CUSTOMERS;

SELECT *
FROM PRODUCTS;

SELECT *
FROM BRANCHES;

SELECT *
FROM SALES
ORDER BY SALE_ID;

SELECT COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS;

SELECT COUNT(*) AS PRODUCT_COUNT
FROM PRODUCTS;

SELECT COUNT(*) AS BRANCH_COUNT
FROM BRANCHES;

SELECT COUNT(*) AS SALES_COUNT
FROM SALES;

-- Phase 3
CREATE OR REPLACE STREAM SALES_STREAM
ON TABLE SALES;

SHOW STREAMS;

DESC STREAM SALES_STREAM;


COPY INTO SALES
FROM @SALES_STAGE/new_sales.csv
FILE_FORMAT = CSV_FORMAT;


SELECT *
FROM SALES
ORDER BY SALE_ID;


SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT
FROM SALES_STREAM
WHERE METADATA$ACTION = 'INSERT';


MERGE INTO SALES AS TARGET
USING SALES_STREAM AS SOURCE
ON TARGET.SALE_ID = SOURCE.SALE_ID

WHEN MATCHED THEN
    UPDATE SET
        TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID,
        TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID,
        TARGET.BRANCH_ID = SOURCE.BRANCH_ID,
        TARGET.QUANTITY = SOURCE.QUANTITY,
        TARGET.SALE_DATE = SOURCE.SALE_DATE,
        TARGET.TOTAL_AMOUNT = SOURCE.TOTAL_AMOUNT

WHEN NOT MATCHED THEN
    INSERT (
        SALE_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        BRANCH_ID,
        QUANTITY,
        SALE_DATE,
        TOTAL_AMOUNT
    )
    VALUES (
        SOURCE.SALE_ID,
        SOURCE.CUSTOMER_ID,
        SOURCE.PRODUCT_ID,
        SOURCE.BRANCH_ID,
        SOURCE.QUANTITY,
        SOURCE.SALE_DATE,
        SOURCE.TOTAL_AMOUNT
    );


SELECT *
FROM SALES
ORDER BY SALE_ID;


SELECT COUNT(*) AS TOTAL_SALES
FROM SALES;

-- Phase 4

SELECT
    SALE_ID,
    COUNT(*) AS ID_COUNT
FROM SALES
GROUP BY SALE_ID
HAVING COUNT(*) > 1;

SELECT DISTINCT
    S.CUSTOMER_ID
FROM SALES S
LEFT JOIN CUSTOMERS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

SELECT DISTINCT
    S.PRODUCT_ID
FROM SALES S
LEFT JOIN PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

SELECT COUNT(*) AS TOTAL_SALES
FROM SALES;

SELECT COUNT(*) AS NEW_SALES_COUNT
FROM SALES
WHERE SALE_ID BETWEEN 6 AND 10;

SELECT
    COUNT(*) AS TOTAL_SALES
FROM SALES;

-- Phase 5

SELECT *
FROM SALES
WHERE SALE_ID = 10;

DELETE FROM SALES
WHERE SALE_ID = 10;

SELECT *
FROM SALES
WHERE SALE_ID = 10;

SELECT *
FROM SALES
AT (
    OFFSET => -300
)
WHERE SALE_ID = 10;

INSERT INTO SALES
SELECT *
FROM SALES
AT (
    OFFSET => -300
)
WHERE SALE_ID = 10;

SELECT *
FROM SALES
WHERE SALE_ID = 10;

-- Phase 6
SELECT COUNT(*) AS TOTAL_SALES
FROM SALES;

SELECT *
FROM SALES
ORDER BY SALE_ID;

CREATE OR REPLACE TABLE SALES_TEST
CLONE SALES;

SHOW TABLES;

SELECT *
FROM SALES_TEST
ORDER BY SALE_ID;

INSERT INTO SALES_TEST (
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT
)
VALUES (
    11,
    1,
    101,
    1,
    1,
    '2026-07-11',
    60000
);

SELECT *
FROM SALES_TEST
ORDER BY SALE_ID;

SELECT COUNT(*) AS CLONE_COUNT
FROM SALES_TEST;

SELECT COUNT(*) AS ORIGINAL_COUNT
FROM SALES;

SELECT *
FROM SALES
WHERE SALE_ID = 11;

SELECT
    'SALES' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM SALES

UNION ALL

SELECT
    'SALES_TEST' AS TABLE_NAME,
    COUNT(*) AS RECORD_COUNT
FROM SALES_TEST;

-- Phase 7
CREATE OR REPLACE TABLE SALES_INCREMENTAL (
    SALE_ID INT,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    QUANTITY INT,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2)
);

CREATE OR REPLACE STREAM SALES_INCREMENTAL_STREAM
ON TABLE SALES_INCREMENTAL;

CREATE OR REPLACE TASK DAILY_SALES_INCREMENT
    WAREHOUSE = ENTERPRISE_WH
    SCHEDULE = 'USING CRON 0 0 * * * UTC'
AS
MERGE INTO SALES AS TARGET
USING SALES_INCREMENTAL_STREAM AS SOURCE
ON TARGET.SALE_ID = SOURCE.SALE_ID

WHEN MATCHED THEN
    UPDATE SET
        TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID,
        TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID,
        TARGET.BRANCH_ID = SOURCE.BRANCH_ID,
        TARGET.QUANTITY = SOURCE.QUANTITY,
        TARGET.SALE_DATE = SOURCE.SALE_DATE,
        TARGET.TOTAL_AMOUNT = SOURCE.TOTAL_AMOUNT

WHEN NOT MATCHED THEN
    INSERT (
        SALE_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        BRANCH_ID,
        QUANTITY,
        SALE_DATE,
        TOTAL_AMOUNT
    )
    VALUES (
        SOURCE.SALE_ID,
        SOURCE.CUSTOMER_ID,
        SOURCE.PRODUCT_ID,
        SOURCE.BRANCH_ID,
        SOURCE.QUANTITY,
        SOURCE.SALE_DATE,
        SOURCE.TOTAL_AMOUNT
    );

SHOW TASKS;

DESC TASK DAILY_SALES_INCREMENT;

ALTER TASK DAILY_SALES_INCREMENT
RESUME;

SHOW TASKS;

INSERT INTO SALES_INCREMENTAL (
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT
)
VALUES (
    12,
    2,
    101,
    2,
    1,
    '2026-07-12',
    60000
);

SELECT *
FROM SALES_INCREMENTAL_STREAM;

EXECUTE TASK DAILY_SALES_INCREMENT;

SELECT *
FROM SALES
WHERE SALE_ID = 12;


SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    QUERY_START_TIME,
    COMPLETED_TIME,
    ERROR_MESSAGE
FROM TABLE(
    INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'DAILY_SALES_INCREMENT',
        RESULT_LIMIT => 10
    )
)
ORDER BY SCHEDULED_TIME DESC;

-- Phase 8
SELECT *
FROM SALES
ORDER BY SALE_ID;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;


SELECT
    DATE_TRUNC('MONTH', SALE_DATE) AS SALES_MONTH,
    SUM(TOTAL_AMOUNT) AS MONTHLY_REVENUE
FROM SALES
GROUP BY DATE_TRUNC('MONTH', SALE_DATE)
ORDER BY SALES_MONTH;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    COUNT(S.SALE_ID) AS PURCHASE_FREQUENCY
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY PURCHASE_FREQUENCY DESC;

SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (
        ORDER BY SALE_DATE, SALE_ID
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS RUNNING_REVENUE
FROM SALES
ORDER BY SALE_DATE, SALE_ID;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

-- Phase 9
SELECT COUNT(*) AS TOTAL_SALES FROM SALES;

DELETE FROM SALES WHERE SALE_ID = 12;

CREATE OR REPLACE VIEW CUSTOMER_REVENUE AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME;

SHOW VIEWS;

DESC VIEW CUSTOMER_REVENUE;

CREATE OR REPLACE MATERIALIZED VIEW BRANCH_REVENUE AS
SELECT
    BRANCH_ID,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES
GROUP BY BRANCH_ID;

SHOW MATERIALIZED VIEWS;

DESC MATERIALIZED VIEW BRANCH_REVENUE;

SELECT *
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

SELECT *
FROM BRANCH_REVENUE
ORDER BY TOTAL_REVENUE DESC;

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    R.TOTAL_REVENUE
FROM BRANCH_REVENUE R
JOIN BRANCHES B
    ON R.BRANCH_ID = B.BRANCH_ID
ORDER BY R.TOTAL_REVENUE DESC;