/* ---------- 2.1 Create Warehouse ---------- */
CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH4
    WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE RETAIL_WH4;


/* ---------- 2.2 Create Database ---------- */

CREATE DATABASE IF NOT EXISTS RETAIL_DB4;

USE DATABASE RETAIL_DB4;


/* ---------- 2.3 Create Schema ---------- */

CREATE SCHEMA IF NOT EXISTS SALES_SCHEMA;

USE SCHEMA SALES_SCHEMA;


/* ---------- 2.4 Create CSV File Format ---------- */

CREATE FILE FORMAT IF NOT EXISTS RETAIL_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE;


/* ---------- 2.5 Create Internal Stage ---------- */

CREATE STAGE IF NOT EXISTS RETAIL_STAGE
    FILE_FORMAT = RETAIL_CSV_FORMAT;




LIST @RETAIL_STAGE;


/* ---------- 2.6 Create Dimension Tables ---------- */

/* Customer Dimension */

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID      NUMBER(38,0) PRIMARY KEY,
    CUSTOMER_NAME    VARCHAR(100),
    CITY             VARCHAR(100),
    STATE            VARCHAR(100),
    MEMBERSHIP       VARCHAR(50)
);


/* Product Dimension */

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID       NUMBER(38,0) PRIMARY KEY,
    PRODUCT_NAME     VARCHAR(100),
    CATEGORY         VARCHAR(100),
    BRAND            VARCHAR(100),
    PRICE            NUMBER(12,2)
);


/* Branch Dimension */

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID        NUMBER(38,0) PRIMARY KEY,
    BRANCH_NAME      VARCHAR(150),
    CITY             VARCHAR(100),
    STATE            VARCHAR(100),
    REGION           VARCHAR(100),
    MANAGER_NAME     VARCHAR(100)
);

/* Date Dimension */

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID          NUMBER(38,0) PRIMARY KEY,
    DATE             DATE,
    DAY              NUMBER(2,0),
    DAY_NAME         VARCHAR(20),
    WEEK_NO          NUMBER(2,0),
    MONTH            VARCHAR(20),
    QUARTER          VARCHAR(10),
    YEAR             NUMBER(4,0),
    IS_WEEKEND       VARCHAR(5)
);


/* ---------- 2.7 Create Fact Table ---------- */

CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID          NUMBER(38,0) PRIMARY KEY,
    CUSTOMER_ID      NUMBER(38,0),
    PRODUCT_ID       NUMBER(38,0),
    BRANCH_ID        NUMBER(38,0),
    DATE_ID          NUMBER(38,0),
    QUANTITY         NUMBER(38,0),
    TOTAL_AMOUNT     NUMBER(14,2),

    CONSTRAINT FK_SALES_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_SALES_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_SALES_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    CONSTRAINT FK_SALES_DATE
        FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);


/* ---------- 2.8 Load CSV Files ---------- */


COPY INTO DIM_CUSTOMER
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO DIM_PRODUCT
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO DIM_BRANCH
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO DIM_DATE
FROM @RETAIL_STAGE/calendar.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO FACT_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';


/* ---------- 2.9 Verify Loaded Data ---------- */

SELECT * FROM DIM_CUSTOMER ORDER BY CUSTOMER_ID;

SELECT * FROM DIM_PRODUCT ORDER BY PRODUCT_ID;

SELECT * FROM DIM_BRANCH ORDER BY BRANCH_ID;

SELECT * FROM DIM_DATE ORDER BY DATE_ID;

SELECT * FROM FACT_SALES ORDER BY SALE_ID;


/* ---------- 2.10 Verify Record Counts ---------- */

SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER

UNION ALL

SELECT 'DIM_PRODUCT', COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT 'DIM_BRANCH', COUNT(*)
FROM DIM_BRANCH

UNION ALL

SELECT 'DIM_DATE', COUNT(*)
FROM DIM_DATE

UNION ALL

SELECT 'FACT_SALES', COUNT(*)
FROM FACT_SALES;



/* ---------- 3.1 Inspect Fact Table Structure ---------- */

DESCRIBE TABLE FACT_SALES;


/* ---------- 3.2 Check Fact Table Grain ---------- */

SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
FROM FACT_SALES
ORDER BY SALE_ID;



/* ---------- 4.1 Inspect Dimensions ---------- */

DESCRIBE TABLE DIM_CUSTOMER;

DESCRIBE TABLE DIM_PRODUCT;

DESCRIBE TABLE DIM_BRANCH;

DESCRIBE TABLE DIM_DATE;


/* ---------- 4.2 Basic Measure Validation ---------- */

SELECT
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES;


/* ---------- 4.3 Measure by Date ---------- */

SELECT
    D.DATE,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY D.DATE
ORDER BY D.DATE;


/* PHASE 5 - GRAIN IDENTIFICATION*/

SELECT
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    COUNT(*) AS ROW_COUNT
FROM FACT_SALES
GROUP BY
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID
HAVING COUNT(*) > 1
ORDER BY ROW_COUNT DESC;


/* PHASE 6 - RELATIONSHIP IDENTIFICATION*/


/* ---------- 6.1 Check Orphan Customer IDs ---------- */

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;


/* ---------- 6.2 Check Orphan Product IDs ---------- */

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;


/* ---------- 6.3 Check Orphan Branch IDs ---------- */

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
WHERE B.BRANCH_ID IS NULL;


/* ---------- 6.4 Check Orphan Date IDs ---------- */

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
WHERE D.DATE_ID IS NULL;


/*PHASE 7 - COMPLETE DIMENSIONAL MODEL*/


/* ---------- 7.1 Complete Joined Fact View ---------- */

CREATE OR REPLACE VIEW SALES_DETAIL AS
SELECT
    F.SALE_ID,

    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY AS CUSTOMER_CITY,
    C.STATE AS CUSTOMER_STATE,
    C.MEMBERSHIP,

    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    P.PRICE,

    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY AS BRANCH_CITY,
    B.STATE AS BRANCH_STATE,

    D.DATE_ID,
    D.DATE,
    D.DAY,
    D.DAY_NAME,
    D.WEEK_NO,
    D.MONTH,
    D.QUARTER,
    D.YEAR,
    D.IS_WEEKEND,

    F.QUANTITY,
    F.TOTAL_AMOUNT

FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID;


/* Verify the complete star-schema join */

SELECT *
FROM SALES_DETAIL
ORDER BY SALE_ID;


/* PHASE 8 - BUSINESS VALIDATION / ANALYTICAL */


/* ---------- 8.1 Customer-wise Sales / Customer Revenue Report ---------- */

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;


/* ---------- 8.2 Product-wise Revenue Report ---------- */

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;


/* ---------- 8.3 Branch-wise Sales / Branch Performance Report ---------- */

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE
ORDER BY TOTAL_REVENUE DESC;


/* ---------- 8.4 Monthly Revenue Report ---------- */

SELECT
    D.YEAR,
    D.MONTH,
    SUM(F.TOTAL_AMOUNT) AS MONTHLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.MONTH
ORDER BY
    D.YEAR,
    MIN(D.DATE);


/* ---------- 8.5 Quarterly Revenue Report ---------- */

SELECT
    D.YEAR,
    D.QUARTER,
    SUM(F.TOTAL_AMOUNT) AS QUARTERLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.QUARTER
ORDER BY
    D.YEAR,
    MIN(D.DATE);


/* ---------- 8.6 State-wise Revenue Report ---------- */

SELECT
    B.STATE,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.STATE
ORDER BY TOTAL_REVENUE DESC;


/* ---------- 8.7 Category-wise Revenue Report ---------- */

SELECT
    P.CATEGORY,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;


/* ---------- 8.8 Top 10 Customers by Total Sales ---------- */

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


/* ---------- 8.9 Top 10 Products by Revenue ---------- */

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


/* ---------- 8.10 Top 10 Performing Branches ---------- */

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.STATE,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.STATE
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


/* ---------- 8.11 Total Business Revenue ---------- */

SELECT
    SUM(TOTAL_AMOUNT) AS TOTAL_BUSINESS_REVENUE
FROM FACT_SALES;


/* ---------- 8.12 Total Units Sold ---------- */

SELECT
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD
FROM FACT_SALES;


/* ---------- 8.13 Customer Purchase Analysis ---------- */

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    COUNT(F.SALE_ID) AS PURCHASE_COUNT,
    SUM(F.QUANTITY) AS TOTAL_UNITS_PURCHASED,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SPENDING,
    AVG(F.TOTAL_AMOUNT) AS AVERAGE_TRANSACTION_VALUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC;


/* ---------- 8.14 Product Performance Dashboard ---------- */

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    COUNT(F.SALE_ID) AS NUMBER_OF_TRANSACTIONS,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND
ORDER BY REVENUE DESC;


/* ---------- 8.15 Branch Performance Dashboard ---------- */

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE,
    COUNT(F.SALE_ID) AS NUMBER_OF_TRANSACTIONS,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS REVENUE,
    AVG(F.TOTAL_AMOUNT) AS AVERAGE_TRANSACTION_VALUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE
ORDER BY REVENUE DESC;


/* ---------- 8.16 Sales Trend Analysis ---------- */

SELECT
    D.DATE,
    SUM(F.QUANTITY) AS DAILY_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS DAILY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY D.DATE
ORDER BY D.DATE;


/* ---------- 8.17 Highest Revenue Customer ---------- */

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
QUALIFY RANK() OVER (
    ORDER BY SUM(F.TOTAL_AMOUNT) DESC
) = 1;


/* ---------- 8.18 Highest Revenue Branch ---------- */

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
QUALIFY RANK() OVER (
    ORDER BY SUM(F.TOTAL_AMOUNT) DESC
) = 1;


/* ---------- 8.19 Customer Ranking ---------- */

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    RANK() OVER (
        ORDER BY SUM(F.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;


/* ---------- 8.20 Product Ranking ---------- */

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    RANK() OVER (
        ORDER BY SUM(F.TOTAL_AMOUNT) DESC
    ) AS PRODUCT_RANK
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY PRODUCT_RANK;


/* ---------- 8.21 Branch Ranking ---------- */

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    RANK() OVER (
        ORDER BY SUM(F.TOTAL_AMOUNT) DESC
    ) AS BRANCH_RANK
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY BRANCH_RANK;


/* ---------- 8.22 Running Revenue / Sales Trend ---------- */

SELECT
    D.DATE,
    SUM(F.TOTAL_AMOUNT) AS DAILY_REVENUE,
    SUM(SUM(F.TOTAL_AMOUNT)) OVER (
        ORDER BY D.DATE
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS RUNNING_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY D.DATE
ORDER BY D.DATE;


/* ---------- 8.23 Average Sale Amount ---------- */

SELECT
    F.SALE_ID,
    F.TOTAL_AMOUNT,
    AVG(F.TOTAL_AMOUNT) OVER () AS AVERAGE_SALE_AMOUNT
FROM FACT_SALES F
ORDER BY F.SALE_ID;


/* ---------- 8.24 Top Product in Each Category ---------- */

SELECT
    CATEGORY,
    PRODUCT_ID,
    PRODUCT_NAME,
    TOTAL_REVENUE
FROM (
    SELECT
        P.CATEGORY,
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE,
        ROW_NUMBER() OVER (
            PARTITION BY P.CATEGORY
            ORDER BY SUM(F.TOTAL_AMOUNT) DESC
        ) AS RN
    FROM FACT_SALES F
    JOIN DIM_PRODUCT P
        ON F.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY
        P.CATEGORY,
        P.PRODUCT_ID,
        P.PRODUCT_NAME
)
WHERE RN = 1
ORDER BY CATEGORY;


/* ---------- 8.25 Customers Spending Above Average ---------- */

WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM FACT_SALES F
    JOIN DIM_CUSTOMER C
        ON F.CUSTOMER_ID = C.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_REVENUE
FROM CUSTOMER_REVENUE
WHERE TOTAL_REVENUE > (
    SELECT AVG(TOTAL_REVENUE)
    FROM CUSTOMER_REVENUE
)
ORDER BY TOTAL_REVENUE DESC;

/* ---------- 8.26 Regional Sales Analysis ----------*/

SELECT
    B.STATE,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    SUM(F.QUANTITY) AS TOTAL_UNITS
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.STATE
ORDER BY TOTAL_REVENUE DESC;


/*OPTIONAL REPORT VIEWS/


/* ---------- 8.27 Customer Revenue View ---------- */

CREATE OR REPLACE VIEW CUSTOMER_REVENUE AS
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.STATE,
    C.MEMBERSHIP,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.STATE,
    C.MEMBERSHIP;


/* ---------- 8.28 Product Revenue View ---------- */

CREATE OR REPLACE VIEW PRODUCT_REVENUE AS
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND;


/* ---------- 8.29 Branch Revenue View ---------- */

CREATE OR REPLACE VIEW BRANCH_REVENUE AS
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    B.STATE;


/* ---------- 8.30 Monthly Revenue View ---------- */

CREATE OR REPLACE VIEW MONTHLY_REVENUE AS
SELECT
    D.YEAR,
    D.MONTH,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.MONTH;


/* ---------- Query the Views ---------- */

SELECT * FROM CUSTOMER_REVENUE ORDER BY TOTAL_REVENUE DESC;

SELECT * FROM PRODUCT_REVENUE ORDER BY TOTAL_REVENUE DESC;

SELECT * FROM BRANCH_REVENUE ORDER BY TOTAL_REVENUE DESC;

SELECT * FROM MONTHLY_REVENUE;


/*FINAL VALIDATION CHECKLIST*/

SELECT COUNT(*) AS CUSTOMERS_LOADED
FROM DIM_CUSTOMER;

SELECT COUNT(*) AS PRODUCTS_LOADED
FROM DIM_PRODUCT;

SELECT COUNT(*) AS BRANCHES_LOADED
FROM DIM_BRANCH;

SELECT COUNT(*) AS DATES_LOADED
FROM DIM_DATE;

SELECT COUNT(*) AS SALES_LOADED
FROM FACT_SALES;


/* Check invalid foreign keys */

SELECT COUNT(*) AS INVALID_CUSTOMER_KEYS
FROM FACT_SALES F
LEFT JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;


SELECT COUNT(*) AS INVALID_PRODUCT_KEYS
FROM FACT_SALES F
LEFT JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;


SELECT COUNT(*) AS INVALID_BRANCH_KEYS
FROM FACT_SALES F
LEFT JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
WHERE B.BRANCH_ID IS NULL;


SELECT COUNT(*) AS INVALID_DATE_KEYS
FROM FACT_SALES F
LEFT JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
WHERE D.DATE_ID IS NULL;


/* Final total */

SELECT
    COUNT(*) AS TOTAL_SALES_TRANSACTIONS,
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(TOTAL_AMOUNT) AS TOTAL_BUSINESS_REVENUE
FROM FACT_SALES;

