--Project 5
--Phase 1
CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH5
    WITH 
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE RETAIL_WH5;

CREATE DATABASE RETAIL_SALES_DB;
USE DATABASE RETAIL_SALES_DB;

CREATE SCHEMA RETAIL_SALES;
USE SCHEMA RETAIL_SALES;

CREATE FILE FORMAT IF NOT EXISTS RETAIL_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE;

CREATE STAGE IF NOT EXISTS RETAIL_STAGE
    FILE_FORMAT = RETAIL_CSV_FORMAT;

LIST @RETAIL_STAGE;

-- Phase 2

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    BRAND VARCHAR,
    PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    REGION VARCHAR,
    MANAGER_NAME VARCHAR
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID NUMBER PRIMARY KEY,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR,
    WEEK_NO NUMBER,
    MONTH VARCHAR,
    QUARTER VARCHAR,
    YEAR NUMBER,
    IS_WEEKEND VARCHAR
);

-- Phase 4
CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(14,2),

    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);

COPY INTO DIM_CUSTOMER
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO DIM_PRODUCT
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO DIM_BRANCH
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO DIM_DATE
FROM @RETAIL_STAGE/calendar.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';


COPY INTO FACT_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

-- Phase 5
SELECT COUNT(*) FROM DIM_CUSTOMER;

SELECT COUNT(*) FROM DIM_PRODUCT;

SELECT COUNT(*) FROM DIM_BRANCH;

SELECT COUNT(*) FROM DIM_DATE;

SELECT COUNT(*) FROM FACT_SALES;

-- Phase 6
SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
WHERE B.BRANCH_ID IS NULL;

SELECT F.*
FROM FACT_SALES F
LEFT JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
WHERE D.DATE_ID IS NULL;

-- Phase 7

-- Customer-wise Sales Report
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, C.MEMBERSHIP, SUM(F.QUANTITY) AS TOTAL_QUANTITY, SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME, C.MEMBERSHIP
ORDER BY TOTAL_SALES DESC;

-- Product-wise Revenue Report
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY, P.BRAND, SUM(F.QUANTITY) AS TOTAL_QUANTITY, SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY, P.BRAND
ORDER BY TOTAL_REVENUE DESC;

-- Branch-wise Revenue Report
SELECT B.BRANCH_ID, B.BRANCH_NAME, B.CITY, B.STATE, B.REGION,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_ID, B.BRANCH_NAME, B.CITY, B.STATE, B.REGION
ORDER BY TOTAL_REVENUE DESC;

-- State-wise Revenue Report
SELECT B.STATE,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.STATE
ORDER BY TOTAL_REVENUE DESC;

-- Monthly Revenue Report
SELECT D.YEAR, D.MONTH,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY D.YEAR, D.MONTH
ORDER BY D.YEAR, MIN(D.DATE);

-- Quarterly Revenue Report
SELECT D.YEAR, D.QUARTER,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY D.YEAR, D.QUARTER
ORDER BY
    D.YEAR,
    D.QUARTER;

-- Top 10 Customers
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- Top 10 Products
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- Top 10 Performing Branches
SELECT
    B.BRANCH_ID, B.BRANCH_NAME, B.STATE, B.REGION,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_ID, B.BRANCH_NAME, B.STATE, B.REGION
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

-- Category-wise Revenue
SELECT P.CATEGORY,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- Customer Purchase Trend
SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, D.DATE,
    SUM(F.QUANTITY) AS QUANTITY_PURCHASED,
    SUM(F.TOTAL_AMOUNT) AS PURCHASE_AMOUNT
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME, D.DATE
ORDER BY C.CUSTOMER_ID, D.DATE;

-- Product Performance Dashboard
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY, P.BRAND,
    COUNT(F.SALE_ID) AS NUMBER_OF_TRANSACTIONS,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(F.TOTAL_AMOUNT) AS AVG_TRANSACTION_VALUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY, P.BRAND
ORDER BY TOTAL_REVENUE DESC;

-- Branch Performance Dashboard
SELECT B.BRANCH_ID, B.BRANCH_NAME, B.CITY, B.STATE, B.REGION,
    COUNT(F.SALE_ID) AS NUMBER_OF_TRANSACTIONS,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(F.TOTAL_AMOUNT) AS AVG_TRANSACTION_VALUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_ID, B.BRANCH_NAME, B.CITY, B.STATE, B.REGION
ORDER BY TOTAL_REVENUE DESC;

-- Regional Sales Analysis
SELECT B.REGION,
    COUNT(DISTINCT B.BRANCH_ID) AS NUMBER_OF_BRANCHES,
    COUNT(F.SALE_ID) AS NUMBER_OF_TRANSACTIONS,
    SUM(F.QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.REGION
ORDER BY TOTAL_REVENUE DESC;

-- Sales Trend Analysis
SELECT D.DATE,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY D.DATE
ORDER BY D.DATE;
