-- Phase 3
CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH6;
USE WAREHOUSE RETAIL_WH6;

CREATE DATABASE IF NOT EXISTS RETAIL_SALES_DB;
USE DATABASE RETAIL_SALES_DB;

CREATE SCHEMA IF NOT EXISTS PROJECT_6;
USE SCHEMA PROJECT_6;

CREATE FILE FORMAT IF NOT EXISTS RETAIL_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE;

CREATE STAGE IF NOT EXISTS RETAIL_STAGE
    FILE_FORMAT = RETAIL_CSV_FORMAT;

LIST @RETAIL_STAGE;

-- Temp Tables
CREATE OR REPLACE TABLE STG_CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR
);

CREATE OR REPLACE TABLE STG_PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    BRAND VARCHAR,
    PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE STG_BRANCHES (
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    REGION VARCHAR,
    MANAGER_NAME VARCHAR
);

CREATE OR REPLACE TABLE STG_CALENDAR (
    DATE_ID NUMBER,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR,
    WEEK_NO NUMBER,
    MONTH VARCHAR,
    QUARTER VARCHAR,
    YEAR NUMBER,
    IS_WEEKEND VARCHAR
);

COPY INTO STG_CUSTOMERS
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO STG_PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO STG_BRANCHES
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO STG_CALENDAR
FROM @RETAIL_STAGE/calendar.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

-- Dim State
CREATE OR REPLACE TABLE DIM_STATE (
    STATE_ID NUMBER AUTOINCREMENT,
    STATE_NAME VARCHAR,

    CONSTRAINT PK_DIM_STATE
        PRIMARY KEY (STATE_ID)
);

INSERT INTO DIM_STATE (STATE_NAME)
SELECT DISTINCT STATE
FROM (
    SELECT STATE FROM STG_CUSTOMERS
    UNION
    SELECT STATE FROM STG_BRANCHES
);

-- Dim City
CREATE OR REPLACE TABLE DIM_CITY (
    CITY_ID NUMBER AUTOINCREMENT,
    CITY_NAME VARCHAR,
    STATE_ID NUMBER,

    CONSTRAINT PK_DIM_CITY
        PRIMARY KEY (CITY_ID),

    CONSTRAINT FK_CITY_STATE
        FOREIGN KEY (STATE_ID)
        REFERENCES DIM_STATE(STATE_ID)
);

INSERT INTO DIM_CITY (
    CITY_NAME,
    STATE_ID
)
SELECT DISTINCT
    X.CITY,
    S.STATE_ID
FROM (
    SELECT CITY, STATE
    FROM STG_CUSTOMERS

    UNION

    SELECT CITY, STATE
    FROM STG_BRANCHES
) X
JOIN DIM_STATE S
    ON X.STATE = S.STATE_NAME;

-- Dim Category
CREATE OR REPLACE TABLE DIM_CATEGORY (
    CATEGORY_ID NUMBER AUTOINCREMENT,
    CATEGORY_NAME VARCHAR,

    CONSTRAINT PK_DIM_CATEGORY
        PRIMARY KEY (CATEGORY_ID)
);

INSERT INTO DIM_CATEGORY (CATEGORY_NAME)
SELECT DISTINCT CATEGORY
FROM STG_PRODUCTS;

-- Dim Brand
CREATE OR REPLACE TABLE DIM_BRAND (
    BRAND_ID NUMBER AUTOINCREMENT,
    BRAND_NAME VARCHAR,
    CATEGORY_ID NUMBER,

    CONSTRAINT PK_DIM_BRAND
        PRIMARY KEY (BRAND_ID),

    CONSTRAINT FK_BRAND_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES DIM_CATEGORY(CATEGORY_ID)
);

INSERT INTO DIM_BRAND (
    BRAND_NAME,
    CATEGORY_ID
)
SELECT DISTINCT
    P.BRAND,
    C.CATEGORY_ID
FROM STG_PRODUCTS P
JOIN DIM_CATEGORY C
    ON P.CATEGORY = C.CATEGORY_NAME;

-- Dim Region
CREATE OR REPLACE TABLE DIM_REGION (
    REGION_ID NUMBER AUTOINCREMENT,
    REGION_NAME VARCHAR,

    CONSTRAINT PK_DIM_REGION
        PRIMARY KEY (REGION_ID)
);

INSERT INTO DIM_REGION (REGION_NAME)
SELECT DISTINCT REGION
FROM STG_BRANCHES;

-- Dim State
ALTER TABLE DIM_STATE
ADD COLUMN REGION_ID NUMBER;

UPDATE DIM_STATE S
SET REGION_ID = R.REGION_ID
FROM (
    SELECT DISTINCT
        STATE,
        REGION
    FROM STG_BRANCHES
) B
JOIN DIM_REGION R
    ON B.REGION = R.REGION_NAME
WHERE S.STATE_NAME = B.STATE;

-- Dim Year
CREATE OR REPLACE TABLE DIM_YEAR (
    YEAR_ID NUMBER AUTOINCREMENT,
    YEAR_VALUE NUMBER,

    CONSTRAINT PK_DIM_YEAR
        PRIMARY KEY (YEAR_ID)
);

INSERT INTO DIM_YEAR (YEAR_VALUE)
SELECT DISTINCT YEAR
FROM STG_CALENDAR;

-- Dim Quarter
CREATE OR REPLACE TABLE DIM_QUARTER (
    QUARTER_ID NUMBER AUTOINCREMENT,
    QUARTER_NAME VARCHAR,
    YEAR_ID NUMBER,

    CONSTRAINT PK_DIM_QUARTER
        PRIMARY KEY (QUARTER_ID),

    CONSTRAINT FK_QUARTER_YEAR
        FOREIGN KEY (YEAR_ID)
        REFERENCES DIM_YEAR(YEAR_ID)
);

INSERT INTO DIM_QUARTER (
    QUARTER_NAME,
    YEAR_ID
)
SELECT DISTINCT
    C.QUARTER,
    Y.YEAR_ID
FROM STG_CALENDAR C
JOIN DIM_YEAR Y
    ON C.YEAR = Y.YEAR_VALUE;

-- Dim Month
CREATE OR REPLACE TABLE DIM_MONTH (
    MONTH_ID NUMBER AUTOINCREMENT,
    MONTH_NAME VARCHAR,
    QUARTER_ID NUMBER,

    CONSTRAINT PK_DIM_MONTH
        PRIMARY KEY (MONTH_ID),

    CONSTRAINT FK_MONTH_QUARTER
        FOREIGN KEY (QUARTER_ID)
        REFERENCES DIM_QUARTER(QUARTER_ID)
);

INSERT INTO DIM_MONTH (
    MONTH_NAME,
    QUARTER_ID
)
SELECT DISTINCT
    C.MONTH,
    Q.QUARTER_ID
FROM STG_CALENDAR C
JOIN DIM_YEAR Y
    ON C.YEAR = Y.YEAR_VALUE
JOIN DIM_QUARTER Q
    ON C.QUARTER = Q.QUARTER_NAME
   AND Q.YEAR_ID = Y.YEAR_ID;

-- Phase 4

-- Dim Customer
CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY_ID NUMBER,
    MEMBERSHIP VARCHAR,

    CONSTRAINT PK_DIM_CUSTOMER
        PRIMARY KEY (CUSTOMER_ID),

    CONSTRAINT FK_CUSTOMER_CITY
        FOREIGN KEY (CITY_ID)
        REFERENCES DIM_CITY(CITY_ID)
);

INSERT INTO DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY_ID,
    MEMBERSHIP
)
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CI.CITY_ID,
    C.MEMBERSHIP
FROM STG_CUSTOMERS C
JOIN DIM_CITY CI
    ON C.CITY = CI.CITY_NAME
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
   AND C.STATE = S.STATE_NAME;

-- Dim Product
CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    BRAND_ID NUMBER,
    PRICE NUMBER(12,2),

    CONSTRAINT PK_DIM_PRODUCT
        PRIMARY KEY (PRODUCT_ID),

    CONSTRAINT FK_PRODUCT_BRAND
        FOREIGN KEY (BRAND_ID)
        REFERENCES DIM_BRAND(BRAND_ID)
);

INSERT INTO DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    BRAND_ID,
    PRICE
)
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_ID,
    P.PRICE
FROM STG_PRODUCTS P
JOIN DIM_BRAND B
    ON P.BRAND = B.BRAND_NAME
JOIN DIM_CATEGORY C
    ON P.CATEGORY = C.CATEGORY_NAME
   AND B.CATEGORY_ID = C.CATEGORY_ID;

-- Dim Branch
CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR,
    CITY_ID NUMBER,
    MANAGER_NAME VARCHAR,

    CONSTRAINT PK_DIM_BRANCH
        PRIMARY KEY (BRANCH_ID),

    CONSTRAINT FK_BRANCH_CITY
        FOREIGN KEY (CITY_ID)
        REFERENCES DIM_CITY(CITY_ID)
);

INSERT INTO DIM_BRANCH (
    BRANCH_ID,
    BRANCH_NAME,
    CITY_ID,
    MANAGER_NAME
)
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    CI.CITY_ID,
    B.MANAGER_NAME
FROM STG_BRANCHES B
JOIN DIM_CITY CI
    ON B.CITY = CI.CITY_NAME
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
   AND B.STATE = S.STATE_NAME;

-- Dim Date
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID NUMBER,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR,
    WEEK_NO NUMBER,
    MONTH_ID NUMBER,
    IS_WEEKEND VARCHAR,

    CONSTRAINT PK_DIM_DATE
        PRIMARY KEY (DATE_ID),

    CONSTRAINT FK_DATE_MONTH
        FOREIGN KEY (MONTH_ID)
        REFERENCES DIM_MONTH(MONTH_ID)
);

INSERT INTO DIM_DATE (
    DATE_ID,
    DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH_ID,
    IS_WEEKEND
)
SELECT
    C.DATE_ID,
    C.DATE,
    C.DAY,
    C.DAY_NAME,
    C.WEEK_NO,
    M.MONTH_ID,
    C.IS_WEEKEND
FROM STG_CALENDAR C
JOIN DIM_YEAR Y
    ON C.YEAR = Y.YEAR_VALUE
JOIN DIM_QUARTER Q
    ON C.QUARTER = Q.QUARTER_NAME
   AND Q.YEAR_ID = Y.YEAR_ID
JOIN DIM_MONTH M
    ON C.MONTH = M.MONTH_NAME
   AND M.QUARTER_ID = Q.QUARTER_ID;

CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID          NUMBER(38,0) PRIMARY KEY,
    CUSTOMER_ID      NUMBER(38,0),
    PRODUCT_ID       NUMBER(38,0),
    BRANCH_ID        NUMBER(38,0),
    DATE_ID          NUMBER(38,0),
    QUANTITY         NUMBER(38,0),
    TOTAL_AMOUNT     NUMBER(14,2),

    CONSTRAINT FK_SALES_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_SALES_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_SALES_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    CONSTRAINT FK_SALES_DATE
        FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);

COPY INTO FACT_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = RETAIL_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

-- Phase 7

-- Customer Reports
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CI.CITY_NAME,
    S.STATE_NAME,
    C.MEMBERSHIP,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_CITY CI
    ON C.CITY_ID = CI.CITY_ID
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    CI.CITY_NAME,
    S.STATE_NAME,
    C.MEMBERSHIP
ORDER BY TOTAL_REVENUE DESC;

-- Product Reports
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_NAME,
    C.CATEGORY_NAME,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRAND B
    ON P.BRAND_ID = B.BRAND_ID
JOIN DIM_CATEGORY C
    ON B.CATEGORY_ID = C.CATEGORY_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    B.BRAND_NAME,
    C.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;

--Branch Reports
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    CI.CITY_NAME,
    S.STATE_NAME,
    R.REGION_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY CI
    ON B.CITY_ID = CI.CITY_ID
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    CI.CITY_NAME,
    S.STATE_NAME,
    R.REGION_NAME
ORDER BY TOTAL_REVENUE DESC;

-- Revenue Reports
SELECT
    Y.YEAR_VALUE,
    Q.QUARTER_NAME,
    M.MONTH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
JOIN DIM_MONTH M
    ON D.MONTH_ID = M.MONTH_ID
JOIN DIM_QUARTER Q
    ON M.QUARTER_ID = Q.QUARTER_ID
JOIN DIM_YEAR Y
    ON Q.YEAR_ID = Y.YEAR_ID
GROUP BY
    Y.YEAR_VALUE,
    Q.QUARTER_NAME,
    M.MONTH_NAME
ORDER BY
    Y.YEAR_VALUE,
    Q.QUARTER_NAME,
    M.MONTH_NAME;

-- Regional Reports
SELECT
    R.REGION_NAME,
    COUNT(DISTINCT B.BRANCH_ID) AS BRANCH_COUNT,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_CITY CI
    ON B.CITY_ID = CI.CITY_ID
JOIN DIM_STATE S
    ON CI.STATE_ID = S.STATE_ID
JOIN DIM_REGION R
    ON S.REGION_ID = R.REGION_ID
GROUP BY R.REGION_NAME
ORDER BY TOTAL_REVENUE DESC;

