CREATE WAREHOUSE IF NOT EXISTS HEALTHCARE_WH
    WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE HEALTHCARE_WH;

CREATE DATABASE IF NOT EXISTS HEALTHCARE_DB;
USE DATABASE HEALTHCARE_DB;

CREATE SCHEMA IF NOT EXISTS HEALTHCARE;
USE SCHEMA HEALTHCARE;

CREATE OR REPLACE FILE FORMAT HEALTHCARE_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE;

CREATE OR REPLACE STAGE HEALTHCARE_STAGE
    FILE_FORMAT = HEALTHCARE_CSV_FORMAT;

LIST @HEALTHCARE_STAGE;

CREATE OR REPLACE TABLE RAW_PATIENTS (
    PATIENT_ID      VARCHAR(20),
    PATIENT_NAME    VARCHAR(100),
    GENDER          VARCHAR(20),
    CITY            VARCHAR(100),
    STATE           VARCHAR(100)
);

CREATE OR REPLACE TABLE RAW_DOCTORS (
    DOCTOR_ID       VARCHAR(20),
    DOCTOR_NAME     VARCHAR(100),
    SPECIALIZATION  VARCHAR(100)
);

CREATE OR REPLACE TABLE RAW_HOSPITALS (
    HOSPITAL_ID     VARCHAR(20),
    HOSPITAL_NAME   VARCHAR(150),
    CITY            VARCHAR(100),
    STATE           VARCHAR(100),
    REGION          VARCHAR(50)
);

CREATE OR REPLACE TABLE RAW_DEPARTMENTS (
    DEPARTMENT_ID   VARCHAR(20),
    DEPARTMENT_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE RAW_TREATMENTS (
    TREATMENT_ID        VARCHAR(20),
    TREATMENT_NAME      VARCHAR(100),
    TREATMENT_CATEGORY  VARCHAR(100)
);

CREATE OR REPLACE TABLE RAW_ADMISSIONS (
    ADMISSION_ID    VARCHAR(20),
    PATIENT_ID      VARCHAR(20),
    DOCTOR_ID       VARCHAR(20),
    HOSPITAL_ID     VARCHAR(20),
    DEPARTMENT_ID   VARCHAR(20),
    ADMISSION_DATE  DATE,
    DISCHARGE_DATE  DATE
);

CREATE OR REPLACE TABLE RAW_BILLING (
    BILLING_ID          VARCHAR(20),
    PATIENT_ID          VARCHAR(20),
    DOCTOR_ID           VARCHAR(20),
    HOSPITAL_ID         VARCHAR(20),
    DEPARTMENT_ID       VARCHAR(20),
    TREATMENT_ID        VARCHAR(20),
    BILLING_DATE        DATE,
    QUANTITY            NUMBER(38,0),
    TREATMENT_AMOUNT    NUMBER(14,2),
    DISCOUNT            NUMBER(14,2)
);


-- LOAD CSV FILES INTO RAW TABLES

TRUNCATE TABLE RAW_PATIENTS;

COPY INTO RAW_PATIENTS
FROM @HEALTHCARE_STAGE/patients.csv
FILE_FORMAT = (FORMAT_NAME = HEALTHCARE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE RAW_DOCTORS;

COPY INTO RAW_DOCTORS
FROM @HEALTHCARE_STAGE/doctors.csv
FILE_FORMAT = (FORMAT_NAME = HEALTHCARE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE RAW_HOSPITALS;

COPY INTO RAW_HOSPITALS
FROM @HEALTHCARE_STAGE/hospitals.csv
FILE_FORMAT = (FORMAT_NAME = HEALTHCARE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE RAW_DEPARTMENTS;

COPY INTO RAW_DEPARTMENTS
FROM @HEALTHCARE_STAGE/departments.csv
FILE_FORMAT = (FORMAT_NAME = HEALTHCARE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE RAW_TREATMENTS;

COPY INTO RAW_TREATMENTS
FROM @HEALTHCARE_STAGE/treatments.csv
FILE_FORMAT = (FORMAT_NAME = HEALTHCARE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE RAW_ADMISSIONS;

COPY INTO RAW_ADMISSIONS
FROM @HEALTHCARE_STAGE/admissions.csv
FILE_FORMAT = (FORMAT_NAME = HEALTHCARE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE RAW_BILLING;
--
COPY INTO RAW_BILLING
FROM @HEALTHCARE_STAGE/billing.csv
FILE_FORMAT = (FORMAT_NAME = HEALTHCARE_CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';


-- CREATE DIMENSION TABLES

CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_KEY     NUMBER(38,0) PRIMARY KEY,
    PATIENT_ID      VARCHAR(20) UNIQUE,
    PATIENT_NAME    VARCHAR(100),
    GENDER          VARCHAR(20),
    CITY            VARCHAR(100),
    STATE           VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_DOCTOR (
    DOCTOR_KEY      NUMBER(38,0) PRIMARY KEY,
    DOCTOR_ID       VARCHAR(20) UNIQUE,
    DOCTOR_NAME     VARCHAR(100),
    SPECIALIZATION  VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_HOSPITAL (
    HOSPITAL_KEY    NUMBER(38,0) PRIMARY KEY,
    HOSPITAL_ID     VARCHAR(20) UNIQUE,
    HOSPITAL_NAME   VARCHAR(150),
    CITY            VARCHAR(100),
    STATE           VARCHAR(100),
    REGION          VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_DEPARTMENT (
    DEPARTMENT_KEY  NUMBER(38,0) PRIMARY KEY,
    DEPARTMENT_ID   VARCHAR(20) UNIQUE,
    DEPARTMENT_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_TREATMENT (
    TREATMENT_KEY       NUMBER(38,0) PRIMARY KEY,
    TREATMENT_ID        VARCHAR(20) UNIQUE,
    TREATMENT_NAME      VARCHAR(100),
    TREATMENT_CATEGORY  VARCHAR(100)
);


-- LOAD DIMENSIONS USING SURROGATE KEYS\

INSERT INTO DIM_PATIENT
SELECT
    ROW_NUMBER() OVER (ORDER BY PATIENT_ID) AS PATIENT_KEY,
    PATIENT_ID,
    PATIENT_NAME,
    GENDER,
    CITY,
    STATE
FROM RAW_PATIENTS;

INSERT INTO DIM_DOCTOR
SELECT
    ROW_NUMBER() OVER (ORDER BY DOCTOR_ID) AS DOCTOR_KEY,
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
FROM RAW_DOCTORS;

INSERT INTO DIM_HOSPITAL
SELECT
    ROW_NUMBER() OVER (ORDER BY HOSPITAL_ID) AS HOSPITAL_KEY,
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    REGION
FROM RAW_HOSPITALS;

INSERT INTO DIM_DEPARTMENT
SELECT
    ROW_NUMBER() OVER (ORDER BY DEPARTMENT_ID) AS DEPARTMENT_KEY,
    DEPARTMENT_ID,
    DEPARTMENT_NAME
FROM RAW_DEPARTMENTS;

INSERT INTO DIM_TREATMENT
SELECT
    ROW_NUMBER() OVER (ORDER BY TREATMENT_ID) AS TREATMENT_KEY,
    TREATMENT_ID,
    TREATMENT_NAME,
    TREATMENT_CATEGORY
FROM RAW_TREATMENTS;


-- CREATE DIM_DATE
-- 2026-01-01 THROUGH 2026-03-31

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY     NUMBER(38,0) PRIMARY KEY,
    FULL_DATE    DATE UNIQUE,
    DAY          NUMBER(2,0),
    DAY_NAME     VARCHAR(20),
    WEEK_NO      NUMBER(2,0),
    MONTH        NUMBER(2,0),
    MONTH_NAME   VARCHAR(20),
    QUARTER      VARCHAR(2),
    YEAR         NUMBER(4,0)
);

INSERT INTO DIM_DATE
SELECT
    TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')) AS DATE_KEY,
    FULL_DATE,
    DAY(FULL_DATE) AS DAY,
    DAYNAME(FULL_DATE) AS DAY_NAME,
    WEEK(FULL_DATE) AS WEEK_NO,
    MONTH(FULL_DATE) AS MONTH,
    MONTHNAME(FULL_DATE) AS MONTH_NAME,
    'Q' || QUARTER(FULL_DATE) AS QUARTER,
    YEAR(FULL_DATE) AS YEAR
FROM (
    SELECT DATEADD(
               DAY,
               SEQ4(),
               '2026-01-01'::DATE
           ) AS FULL_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 90))
)
WHERE FULL_DATE <= '2026-03-31'::DATE;


-- BUSINESS PROCESSES

CREATE OR REPLACE TABLE BUSINESS_PROCESSES (
    PROCESS_ID      NUMBER,
    BUSINESS_PROCESS VARCHAR(100)
);

INSERT INTO BUSINESS_PROCESSES VALUES
(1, 'Patient Admissions'),
(2, 'Medical Billing');

SELECT *
FROM BUSINESS_PROCESSES
ORDER BY PROCESS_ID;


-- CREATE FACT_ADMISSION

CREATE OR REPLACE TABLE FACT_ADMISSION (
    ADMISSION_KEY   NUMBER(38,0) PRIMARY KEY,
    PATIENT_KEY     NUMBER(38,0),
    DOCTOR_KEY      NUMBER(38,0),
    HOSPITAL_KEY    NUMBER(38,0),
    DEPARTMENT_KEY  NUMBER(38,0),
    DATE_KEY        NUMBER(38,0),
    ADMISSION_COUNT NUMBER(38,0),
    LENGTH_OF_STAY  NUMBER(38,0),

    CONSTRAINT FK_ADMISSION_PATIENT
        FOREIGN KEY (PATIENT_KEY) REFERENCES DIM_PATIENT(PATIENT_KEY),

    CONSTRAINT FK_ADMISSION_DOCTOR
        FOREIGN KEY (DOCTOR_KEY) REFERENCES DIM_DOCTOR(DOCTOR_KEY),

    CONSTRAINT FK_ADMISSION_HOSPITAL
        FOREIGN KEY (HOSPITAL_KEY) REFERENCES DIM_HOSPITAL(HOSPITAL_KEY),

    CONSTRAINT FK_ADMISSION_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_KEY) REFERENCES DIM_DEPARTMENT(DEPARTMENT_KEY),

    CONSTRAINT FK_ADMISSION_DATE
        FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY)
);


-- FACT_ADMISSION GRAIN

-- LOAD FACT_ADMISSION

INSERT INTO FACT_ADMISSION
SELECT
    ROW_NUMBER() OVER (ORDER BY A.ADMISSION_ID) AS ADMISSION_KEY,
    P.PATIENT_KEY,
    D.DOCTOR_KEY,
    H.HOSPITAL_KEY,
    DP.DEPARTMENT_KEY,
    DT.DATE_KEY,
    1 AS ADMISSION_COUNT,
    DATEDIFF(DAY, A.ADMISSION_DATE, A.DISCHARGE_DATE) AS LENGTH_OF_STAY
FROM RAW_ADMISSIONS A
JOIN DIM_PATIENT P
    ON A.PATIENT_ID = P.PATIENT_ID
JOIN DIM_DOCTOR D
    ON A.DOCTOR_ID = D.DOCTOR_ID
JOIN DIM_HOSPITAL H
    ON A.HOSPITAL_ID = H.HOSPITAL_ID
JOIN DIM_DEPARTMENT DP
    ON A.DEPARTMENT_ID = DP.DEPARTMENT_ID
JOIN DIM_DATE DT
    ON A.ADMISSION_DATE = DT.FULL_DATE;


-- CREATE FACT_BILLING

CREATE OR REPLACE TABLE FACT_BILLING (
    BILLING_KEY       NUMBER(38,0) PRIMARY KEY,
    PATIENT_KEY       NUMBER(38,0),
    DOCTOR_KEY        NUMBER(38,0),
    HOSPITAL_KEY      NUMBER(38,0),
    DEPARTMENT_KEY    NUMBER(38,0),
    TREATMENT_KEY     NUMBER(38,0),
    DATE_KEY          NUMBER(38,0),
    QUANTITY          NUMBER(38,0),
    TREATMENT_AMOUNT  NUMBER(14,2),
    DISCOUNT          NUMBER(14,2),
    NET_AMOUNT        NUMBER(14,2),

    CONSTRAINT FK_BILLING_PATIENT
        FOREIGN KEY (PATIENT_KEY) REFERENCES DIM_PATIENT(PATIENT_KEY),

    CONSTRAINT FK_BILLING_DOCTOR
        FOREIGN KEY (DOCTOR_KEY) REFERENCES DIM_DOCTOR(DOCTOR_KEY),

    CONSTRAINT FK_BILLING_HOSPITAL
        FOREIGN KEY (HOSPITAL_KEY) REFERENCES DIM_HOSPITAL(HOSPITAL_KEY),

    CONSTRAINT FK_BILLING_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_KEY) REFERENCES DIM_DEPARTMENT(DEPARTMENT_KEY),

    CONSTRAINT FK_BILLING_TREATMENT
        FOREIGN KEY (TREATMENT_KEY) REFERENCES DIM_TREATMENT(TREATMENT_KEY),

    CONSTRAINT FK_BILLING_DATE
        FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY)
);


-- FACT_BILLING GRAIN

 INSERT INTO FACT_BILLING
 SELECT
     ROW_NUMBER() OVER (ORDER BY B.BILLING_ID) AS BILLING_KEY,
     P.PATIENT_KEY,
     D.DOCTOR_KEY,
     H.HOSPITAL_KEY,
     DP.DEPARTMENT_KEY,
     T.TREATMENT_KEY,
     DD.DATE_KEY,
     B.QUANTITY,
     B.TREATMENT_AMOUNT,
     B.DISCOUNT,
     B.TREATMENT_AMOUNT - B.DISCOUNT AS NET_AMOUNT
 FROM RAW_BILLING B
 JOIN DIM_PATIENT P
     ON B.PATIENT_ID = P.PATIENT_ID
 JOIN DIM_DOCTOR D
     ON B.DOCTOR_ID = D.DOCTOR_ID
 JOIN DIM_HOSPITAL H
     ON B.HOSPITAL_ID = H.HOSPITAL_ID
 JOIN DIM_DEPARTMENT DP
     ON B.DEPARTMENT_ID = DP.DEPARTMENT_ID
 JOIN DIM_TREATMENT T
     ON B.TREATMENT_ID = T.TREATMENT_ID
 JOIN DIM_DATE DD
      ON B.BILLING_DATE = DD.FULL_DATE;


-- MEASURES

CREATE OR REPLACE TABLE FACT_MEASURES (
    FACT_NAME       VARCHAR(50),
    MEASURE_NAME    VARCHAR(50),
    ADDITIVITY      VARCHAR(20)
);

INSERT INTO FACT_MEASURES VALUES
('FACT_ADMISSION', 'ADMISSION_COUNT', 'Additive'),
('FACT_ADMISSION', 'LENGTH_OF_STAY', 'Additive'),
('FACT_BILLING', 'QUANTITY', 'Additive'),
('FACT_BILLING', 'TREATMENT_AMOUNT', 'Additive'),
('FACT_BILLING', 'DISCOUNT', 'Additive'),
('FACT_BILLING', 'NET_AMOUNT', 'Additive');

SELECT *
FROM FACT_MEASURES
ORDER BY FACT_NAME, MEASURE_NAME;


-- CONFORMED DIMENSIONS

CREATE OR REPLACE TABLE CONFORMED_DIMENSIONS (
    DIMENSION_NAME  VARCHAR(50),
    FACT_ADMISSION  VARCHAR(1),
    FACT_BILLING    VARCHAR(1)
);

INSERT INTO CONFORMED_DIMENSIONS VALUES
('DIM_PATIENT',    'Y', 'Y'),
('DIM_DOCTOR',     'Y', 'Y'),
('DIM_HOSPITAL',   'Y', 'Y'),
('DIM_DEPARTMENT', 'Y', 'Y'),
('DIM_DATE',       'Y', 'Y'),
('DIM_TREATMENT',  'N', 'Y');

SELECT *
FROM CONFORMED_DIMENSIONS
ORDER BY DIMENSION_NAME;

-- ADMISSION ANALYTICS

SELECT
    H.HOSPITAL_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_ADMISSIONS DESC, H.HOSPITAL_NAME;


-- ADDITIONAL ADMISSION ANALYTICS

-- Admissions by department
SELECT
    DP.DEPARTMENT_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_DEPARTMENT DP
    ON F.DEPARTMENT_KEY = DP.DEPARTMENT_KEY
GROUP BY DP.DEPARTMENT_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

-- Admissions by doctor
SELECT
    D.DOCTOR_NAME,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_DOCTOR D
    ON F.DOCTOR_KEY = D.DOCTOR_KEY
GROUP BY D.DOCTOR_NAME
ORDER BY TOTAL_ADMISSIONS DESC;

-- Monthly admissions
SELECT
    TO_CHAR(DD.FULL_DATE, 'YYYY-MM') AS MONTH,
    SUM(F.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION F
JOIN DIM_DATE DD
    ON F.DATE_KEY = DD.DATE_KEY
GROUP BY TO_CHAR(DD.FULL_DATE, 'YYYY-MM')
ORDER BY MONTH;

-- Length of stay by hospital
SELECT
    H.HOSPITAL_NAME,
    SUM(F.LENGTH_OF_STAY) AS TOTAL_LENGTH_OF_STAY
FROM FACT_ADMISSION F
JOIN DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_LENGTH_OF_STAY DESC;


-- HOSPITAL REVENUE ANALYTICS

SELECT
    H.HOSPITAL_NAME,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_HOSPITAL H
    ON F.HOSPITAL_KEY = H.HOSPITAL_KEY
GROUP BY H.HOSPITAL_NAME
ORDER BY TOTAL_REVENUE DESC;


-- MONTHLY REVENUE

SELECT
    TO_CHAR(DD.FULL_DATE, 'YYYY-MM') AS MONTH,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_DATE DD
    ON F.DATE_KEY = DD.DATE_KEY
GROUP BY TO_CHAR(DD.FULL_DATE, 'YYYY-MM')
ORDER BY MONTH;


-- DOCTOR-WISE REVENUE
SELECT
    D.DOCTOR_NAME AS DOCTOR,
    SUM(F.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING F
JOIN DIM_DOCTOR D
    ON F.DOCTOR_KEY = D.DOCTOR_KEY
GROUP BY D.DOCTOR_NAME
ORDER BY TOTAL_REVENUE DESC;


-- DRILL-ACROSS ANALYSIS

WITH ADMISSIONS AS (
    SELECT
        HOSPITAL_KEY,
        SUM(ADMISSION_COUNT) AS TOTAL_ADMISSIONS
    FROM FACT_ADMISSION
    GROUP BY HOSPITAL_KEY
),
BILLING AS (
    SELECT
        HOSPITAL_KEY,
        SUM(NET_AMOUNT) AS TOTAL_REVENUE
    FROM FACT_BILLING
    GROUP BY HOSPITAL_KEY
)
SELECT
    H.HOSPITAL_NAME,
    COALESCE(A.TOTAL_ADMISSIONS, 0) AS TOTAL_ADMISSIONS,
    COALESCE(B.TOTAL_REVENUE, 0) AS TOTAL_REVENUE
FROM DIM_HOSPITAL H
LEFT JOIN ADMISSIONS A
    ON H.HOSPITAL_KEY = A.HOSPITAL_KEY
LEFT JOIN BILLING B
    ON H.HOSPITAL_KEY = B.HOSPITAL_KEY
ORDER BY H.HOSPITAL_NAME;


--BUS MATRIX

SELECT
    DIMENSION_NAME,
    FACT_ADMISSION,
    FACT_BILLING
FROM CONFORMED_DIMENSIONS
ORDER BY
    CASE DIMENSION_NAME
        WHEN 'DIM_PATIENT' THEN 1
        WHEN 'DIM_DOCTOR' THEN 2
        WHEN 'DIM_HOSPITAL' THEN 3
        WHEN 'DIM_DEPARTMENT' THEN 4
        WHEN 'DIM_DATE' THEN 5
        WHEN 'DIM_TREATMENT' THEN 6
    END;


-- ============================================================
-- VALIDATION QUERIES
-- ============================================================

-- Dimension row counts
SELECT 'DIM_PATIENT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIM_PATIENT
UNION ALL
SELECT 'DIM_DOCTOR', COUNT(*) FROM DIM_DOCTOR
UNION ALL
SELECT 'DIM_HOSPITAL', COUNT(*) FROM DIM_HOSPITAL
UNION ALL
SELECT 'DIM_DEPARTMENT', COUNT(*) FROM DIM_DEPARTMENT
UNION ALL
SELECT 'DIM_TREATMENT', COUNT(*) FROM DIM_TREATMENT
UNION ALL
SELECT 'DIM_DATE', COUNT(*) FROM DIM_DATE
ORDER BY TABLE_NAME;



-- Admission fact validation
SELECT
    COUNT(*) AS FACT_ADMISSION_ROWS,
    SUM(ADMISSION_COUNT) AS TOTAL_ADMISSIONS,
    SUM(LENGTH_OF_STAY) AS TOTAL_LENGTH_OF_STAY
FROM FACT_ADMISSION;


-- Referential-integrity style checks
SELECT COUNT(*) AS INVALID_PATIENT_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_PATIENT D
    ON F.PATIENT_KEY = D.PATIENT_KEY
WHERE D.PATIENT_KEY IS NULL;

SELECT COUNT(*) AS INVALID_DOCTOR_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_DOCTOR D
    ON F.DOCTOR_KEY = D.DOCTOR_KEY
WHERE D.DOCTOR_KEY IS NULL;

SELECT COUNT(*) AS INVALID_HOSPITAL_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_HOSPITAL D
    ON F.HOSPITAL_KEY = D.HOSPITAL_KEY
WHERE D.HOSPITAL_KEY IS NULL;

SELECT COUNT(*) AS INVALID_DEPARTMENT_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_DEPARTMENT D
    ON F.DEPARTMENT_KEY = D.DEPARTMENT_KEY
WHERE D.DEPARTMENT_KEY IS NULL;

SELECT COUNT(*) AS INVALID_DATE_KEYS
FROM FACT_ADMISSION F
LEFT JOIN DIM_DATE D
    ON F.DATE_KEY = D.DATE_KEY
WHERE D.DATE_KEY IS NULL;

