
-- TASK 1 — Create Snowflake Database and Schema

CREATE WAREHOUSE IF NOT EXISTS SCD1;
USE WAREHOUSE SCD1; 

CREATE DATABASE IF NOT EXISTS CUSTOMER_SCD_DB;
USE DATABASE CUSTOMER_SCD_DB;

CREATE SCHEMA IF NOT EXISTS SCD_SCHEMA;
USE SCHEMA SCD_SCHEMA;

-- TASK 2 — Create Initial Customer Dimension

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY   NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_ID    NUMBER,
    CUSTOMER_NAME  STRING,
    CITY           STRING,
    STATE          STRING,
    MEMBERSHIP     STRING,
    SEGMENT        STRING
);

-- TASK 3 — Load Initial Customer Data

CREATE OR REPLACE FILE FORMAT CSV_FF
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE CUSTOMER_STAGE
    FILE_FORMAT = CSV_FF;

COPY INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
FROM @CUSTOMER_STAGE/customers_initial.csv.gz
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';

SELECT 'Initial Customer Records Loaded Successfully' AS STATUS,
       COUNT(*) AS TOTAL_CUSTOMERS
FROM DIM_CUSTOMER;


-- TASK 4 — Display Initial Customer Dimension

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

-- TASK 5 — Load Customer Updates into staging table

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID    NUMBER,
    CUSTOMER_NAME  STRING,
    CITY           STRING,
    STATE          STRING,
    MEMBERSHIP     STRING,
    SEGMENT        STRING
);


COPY INTO CUSTOMER_UPDATES (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
FROM @CUSTOMER_STAGE/customer_updates.csv.gz
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';

SELECT 'Customer Update Records Loaded Successfully' AS STATUS,
       COUNT(*) AS RECORDS_RECEIVED
FROM CUSTOMER_UPDATES;


--   TASK 6 — Identify Changed Customers

SELECT
    d.CUSTOMER_ID,
    d.CITY         AS OLD_CITY,
    u.CITY         AS NEW_CITY,
    d.MEMBERSHIP   AS OLD_MEMBERSHIP,
    u.MEMBERSHIP   AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE  d.CITY        <> u.CITY
    OR d.STATE       <> u.STATE
    OR d.MEMBERSHIP  <> u.MEMBERSHIP
    OR d.SEGMENT     <> u.SEGMENT
ORDER BY d.CUSTOMER_ID;

-- TASK 7 — Identify Attribute Changes (change report, one row
   
SELECT CUSTOMER_ID, ATTRIBUTE, OLD_VALUE, NEW_VALUE FROM (
    SELECT d.CUSTOMER_ID, 'CITY' AS ATTRIBUTE, d.CITY AS OLD_VALUE, u.CITY AS NEW_VALUE
    FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
    WHERE d.CITY <> u.CITY

    UNION ALL

    SELECT d.CUSTOMER_ID, 'STATE', d.STATE, u.STATE
    FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
    WHERE d.STATE <> u.STATE

    UNION ALL

    SELECT d.CUSTOMER_ID, 'MEMBERSHIP', d.MEMBERSHIP, u.MEMBERSHIP
    FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
    WHERE d.MEMBERSHIP <> u.MEMBERSHIP

    UNION ALL

    SELECT d.CUSTOMER_ID, 'SEGMENT', d.SEGMENT, u.SEGMENT
    FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
    WHERE d.SEGMENT <> u.SEGMENT
)
ORDER BY CUSTOMER_ID,
         DECODE(ATTRIBUTE, 'CITY', 1, 'STATE', 2, 'MEMBERSHIP', 3, 'SEGMENT', 4);

-- TASK 8 — Demonstrate the SCD Problem

UPDATE DIM_CUSTOMER d
SET d.CITY        = u.CITY,
    d.STATE       = u.STATE,
    d.MEMBERSHIP  = u.MEMBERSHIP,
    d.SEGMENT     = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;


-- TASK 9 — Display the Updated Dimension

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

-- TASK 10 — Demonstrate Historical Data Loss

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;
