-- Create Database and Schema

CREATE DATABASE IF NOT EXISTS CUSTOMER_SCD_DB;
USE DATABASE CUSTOMER_SCD_DB;

CREATE SCHEMA IF NOT EXISTS SCD_SCHEMA;
USE SCHEMA SCD_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FF
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE CUSTOMER_STAGE
    FILE_FORMAT = CSV_FF;


-- Create SCD Type 1 Table

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE1 (
    CUSTOMER_KEY   NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_ID    NUMBER,
    CUSTOMER_NAME  VARCHAR(100),
    CITY           VARCHAR(50),
    STATE          VARCHAR(50),
    MEMBERSHIP     VARCHAR(30),
    SEGMENT        VARCHAR(30)
);


-- Load Initial Type 1 Data

COPY INTO DIM_CUSTOMER_TYPE1 (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
FROM @CUSTOMER_STAGE/customers_initial.csv.gz
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';

SELECT 'Initial Type 1 Records Loaded' AS STATUS, COUNT(*) AS TOTAL_RECORDS
FROM DIM_CUSTOMER_TYPE1;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR(100),
    CITY            VARCHAR(50),
    STATE           VARCHAR(50),
    MEMBERSHIP      VARCHAR(30),
    SEGMENT         VARCHAR(30),
    EFFECTIVE_DATE  DATE
);

COPY INTO CUSTOMER_UPDATES (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT, EFFECTIVE_DATE)
FROM @CUSTOMER_STAGE/customer_updates.csv.gz
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';


-- Apply SCD Type 1 Updates

-- Before:
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID IN (101, 103, 104)
ORDER BY CUSTOMER_ID;

UPDATE DIM_CUSTOMER_TYPE1 d
SET d.CITY        = u.CITY,
    d.STATE       = u.STATE,
    d.MEMBERSHIP  = u.MEMBERSHIP,
    d.SEGMENT     = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

-- After:
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID IN (101, 103, 104)
ORDER BY CUSTOMER_ID;


-- Display Type 1 Result

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;

-- Demonstrate Type 1 History Loss

SELECT CUSTOMER_ID, CITY, STATE, MEMBERSHIP
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID = 101;


-- Create SCD Type 2 Table
  
CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE2 (
    CUSTOMER_KEY    NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR(100),
    CITY            VARCHAR(50),
    STATE           VARCHAR(50),
    MEMBERSHIP      VARCHAR(30),
    SEGMENT         VARCHAR(30),
    EFFECTIVE_DATE  DATE,
    EXPIRY_DATE     DATE,
    IS_CURRENT      BOOLEAN
);

DESC TABLE DIM_CUSTOMER_TYPE2;

--Load Initial Type 2 Records
  
INSERT INTO DIM_CUSTOMER_TYPE2
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT,
     EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT,
    DATE '2026-01-01'  AS EFFECTIVE_DATE,
    DATE '9999-12-31'  AS EXPIRY_DATE,
    TRUE               AS IS_CURRENT
FROM DIM_CUSTOMER_TYPE1;
SELECT 'Initial SCD Type 2 Records Loaded' AS STATUS,
       COUNT(*) AS TOTAL_RECORDS,
       SUM(IFF(IS_CURRENT, 1, 0)) AS CURRENT_RECORDS
FROM DIM_CUSTOMER_TYPE2;


-- Apply Type 2 Changes
-- Step 1: Expire old records
UPDATE DIM_CUSTOMER_TYPE2 d
SET d.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    d.IS_CURRENT  = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT  = TRUE;

-- Step 2: Insert new current records
INSERT INTO DIM_CUSTOMER_TYPE2
    (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT,
     EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    u.CUSTOMER_ID, u.CUSTOMER_NAME, u.CITY, u.STATE, u.MEMBERSHIP, u.SEGMENT,
    u.EFFECTIVE_DATE,
    DATE '9999-12-31' AS EXPIRY_DATE,
    TRUE               AS IS_CURRENT
FROM CUSTOMER_UPDATES u;


-- Customer 101 Type 2 Change

SELECT CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

-- Customer 103 Type 2 Change
  
SELECT CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 103
ORDER BY EFFECTIVE_DATE;

-- Customer 104 Type 2 Change
  
SELECT CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 104
ORDER BY EFFECTIVE_DATE;

-- Display Complete Type 2 History
  
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP,
       EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- Display Current Customer Records

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


--TASK 16 — Historical Customer Analysis

SELECT CUSTOMER_ID, CUSTOMER_NAME, MEMBERSHIP, CITY, EFFECTIVE_DATE, EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
  AND DATE '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

-- Compare Type 1 vs Type 2
  

SELECT * FROM (
    SELECT 'Old value preserved?' AS FEATURE, 'No'  AS TYPE_1, 'Yes' AS TYPE_2
    UNION ALL SELECT 'New row created?',      'No',  'Yes'
    UNION ALL SELECT 'Historical analysis?',  'No',  'Yes'
    UNION ALL SELECT 'Effective Date',        'No',  'Yes'
    UNION ALL SELECT 'Expiry Date',           'No',  'Yes'
    UNION ALL SELECT 'IS_CURRENT',            'No',  'Yes'
    UNION ALL SELECT 'Storage required',      'Lower','Higher'
);

-- Final Validation

SELECT 'SCD TYPE 1 RECORD COUNT' AS METRIC, COUNT(*) AS VALUE
FROM DIM_CUSTOMER_TYPE1

UNION ALL

SELECT 'SCD TYPE 2 RECORD COUNT', COUNT(*)
FROM DIM_CUSTOMER_TYPE2

UNION ALL

SELECT 'SCD TYPE 2 CURRENT RECORD COUNT', COUNT(*)
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT 'SCD TYPE 2 HISTORICAL RECORD COUNT', COUNT(*)
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = FALSE;
